### ISSUE TITLE
Label Designation for Further Use

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#1]
- [x] Kristina
- [x] Taha

**Comment by kristinatrajkovski** [comment]
Added new labels:

-ASAP: intended for urgent fixes, high priority
-design: describes design decisions, appearance fixes etc.
-discussion: expects input from multiple teammates, brainstorming, suggestions
-time consuming: major task which requires time management, splitting up...

**Comment by kristinatrajkovski** [comment]
Closing the issue for now, feel free to add more labels and make suggestions about them as we move along the project.

**Comment by kristinatrajkovski** [comment]
Added "Research" as suggested in class for exploring, researching related topics and similar activities.
