### ISSUE TITLE
Add weekly progress to your wiki pages 

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#10]
- [x] Mehmet Emin İpekdal
- [x] Halil Karabacak
- [x] Mustafa Atak
- [x] Yiğit Poyrazoğlu
- [x] Taha Topaloğlu
- [x] Berkay Keskin
- [x] Eray Eroğlu
- [x] Ceylin Gebeş
- [x] Kristina Trajkovski
- [x] Ahmet Burak Çiçek

**Comment by Mutti499** [comment]
Please do it until tonight!

**Comment by Mutti499** [comment]
Great! 💯

**Comment by ahmetcicekk006** [comment]
my name is not on the list
