### ISSUE TITLE
[Mutti] Create new issue type: "Tracker Issues"

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#105]
We have some issues that are not a real issue instead they are created to keep track of others issues when a task needs to be done by everyone on the team. To distinguish from others, we need to create a new label and assign old tracker issues with them so that it wont be confused with normal issue
Additionally issue template needs to be designed. To do that a team must work on it! We need to inform them.

Estimated time: 10 minute for the tagging
Deadline: 19/03/2024

**Comment by Mutti499** [comment]
tagging completed. Information about task is given at task #43. Rest will be done from here

**Comment by uskudarli** [comment]
What about the issue template?

**Comment by Mutti499** [comment]
Issue template will be done at #43 by my friends you can check the comments as I informed them. This task is used for informing part to avoid duplication of the task. I can keep it open until we complete it from that task if you want  @uskudarli.

**Comment by uskudarli** [comment]
It's OK.

I'm impressed.

Let's keep in touch about this.

**Comment by Mutti499** [comment]
Certainly! I'm tagging the dedicated team and will keep the topic open for a while to expand the scope of this issue regarding Tracker Issues.

@ErayEroglu @ceylingebes

**Comment by Mutti499** [comment]
[New Tracker Issue Template](https://github.com/bounswe/bounswe2024group9/blob/main/.github/ISSUE_TEMPLATE/tracker_issue_template.md) added to the issue templates ! @uskudarli You can review it if you want. Any feedback would be helpful. I will close this issue tomorrow if no change is made.

**Comment by uskudarli** [comment]
Ok.

I will be curious to see how it works in action. Keep me updated when you gain insight please

**Comment by halil-karabacak** [comment]
Great stuff Mutti, hoping this new template will make things easier for the project!

**Comment by Mutti499** [comment]
Thanks mate. It is very valuable to receive your comments.
