### ISSUE TITLE
[Mutti] URGENT REVIEW OF DELIVERABLES

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#107]
#### There are structural errors in our deliverables. NEEDS URGENT REVIEW. I will review all of the following:

- [ ] Requirements
- [ ] Elicitation
- [ ] Chart

* Deadline: 24/03/2024

**Comment by halil-karabacak** [comment]
Hey, how you get that info? I checked my mails and discord notifications but nothing seems to be shared with me.

**Comment by Mutti499** [comment]
I just noticed while I am studying the topics. A few questions in elicitation are how-based questions instead of what-based questions. Needs to be controlled I guess. At the same time, I noticed that there are 2 sub topic under Functional reqirements called User and System reqs.  There may be errors in some requirement titles that I contributed to. I need to check this to avoid any deliverable problems.
Nothing seems to be problematic at the moment but it would still be best to take a look and avoid major mishaps.

**Comment by halil-karabacak** [comment]
Okey, good catch. I will re-check my parts as well and share with you in this issue if I notice an error. But in case of a change, I guess we should also inform teaching-stuff as well.

**Comment by Mutti499** [comment]
Wow I didn't know that. Let's talk to them before we proceed

**Comment by Mutti499** [comment]
Okey we got our feedback and will handle this issues at #113 #112 #111. We can follow the situation from there! So I'll close this issue.
