### ISSUE TITLE
Revise the Requirements

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#111]
We should not organize feedback groupings and questions that fall on us using the feedback we receive. Later, we will open a private issue for others so that they can review and fix the requirements in the structure we have edited! It may seem difficult but we are a strong and cool duo!

Estimated Effort : 2:30 hours
Deadline: 07.03.2024

**Comment by Mutti499** [comment]
I forgot to add my favorite teammate as a reviewer.
@kristinatrajkovski will make sure everything is correct!

**Comment by Mutti499** [comment]
Now that our exams are over, it's time to focus on what really matters. How about a quick chat tomorrow about how to move forward? @halil-karabacak

**Comment by halil-karabacak** [comment]
yeah sorry for being late, that would be great. we can meet today and make a thorough revision. meantime i will read requirements and meeting notes to remember what was wrong.

**Comment by Mutti499** [comment]
Thank you for Information @halil-karabacak. It ıs almost ready. When it finishes we will take a final look.

**Comment by poyrazogluyigit** [comment]
When do you think will it be finished? As it stands, several points discussed in feedback meeting are missing (for instance, some requirements are not in correct format and the discussion regarding different user types seems to have taken no effect -similarly about having realistic requirements); an updated requirements page would be more helpful in design stage.

**Comment by Mutti499** [comment]
I am trying to finish it but order and writing of requirements is drove me crazy. I will literally do the regrouping and leave it. This needs to be talked urgently in the next meeting. This job is an extremely heavy burden for 2 people.

**Comment by Mutti499** [comment]
For now regrouping is completed it will be placed over old requirements after the review of @halil-karabacak especially for 1.1.5.2.

**Comment by Mutti499** [comment]
In the meantime I want to go over some unclear fields here. These needs to be explained by requirements team or whoever wrote them:

1. **1.1.1.2.2 Basic users should be able to get mails about important actions on their accounts and recommended routes.**
   - **Clarification Needed**: Define what constitutes "important actions". For instance, are these actions related to security (e.g., unauthorized login attempts), social interactions (e.g., a new follower or like), or account changes (e.g., password changes)?

2. **1.1.3.1.5 If a user flags a post as "Not interested", then the route in question should be removed from the page immediately.**
   - **Clarification Needed**: Specify the scope and permanence of this action. Does this mean the route is permanently hidden from the user's feed, or does it affect the visibility for a certain period? Also, is there a mechanism for the user to undo this action?

3. **1.1.3.2.2 All routes should be sorted with respect to several different criteria such as most routed, most rerouted, longest route, etc.**
   - **Clarification Needed**: Detail out all the criteria available for sorting. Additionally, indicate whether users can customize these criteria or if there are default settings. How the system prioritizes or combines these criteria for displaying results could also be addressed.

4. **1.1.3.3.1 Each POI must have its own page; this page includes a general information section about the POI, comments of users about this POI, etc. (tentative)**
   - **Clarification Needed**: Define the structure of the POI page more clearly. What specific information is included in the general information section? Are there any limitations or guidelines for the comments section?

5. **1.1.4.1.4 The user shall be able to import/export routes.**
   - **Clarification Needed**: Specify the formats supported for import and export. Also, consider detailing the process or requirements for these actions, such as whether there are any restrictions on the size or type of data that can be imported/exported.

6. **1.1.5.2.1 There shall be a filtering system which uses several criteria like location, type of activity, and user ratings.**
   - **Clarification Needed**: Expand on how the filtering system works. Are filters applied cumulatively or individually? Can users apply multiple filters simultaneously, and if so, how does the system resolve conflicts or prioritize results?

7. **1.1.8.1.3 The users shall be able to download maps for offline use.**
   - **Clarification Needed**: Detail the extent of map functionality available offline. For example, does it include real-time location tracking, route planning, or just static map viewing? Also, specify any limitations of offline maps, such as the frequency of updates or geographical restrictions.

**Comment by halil-karabacak** [comment]
That was a good team work mutti!

**Comment by Mutti499** [comment]
Ye mate! We regrouped our requirements from the start! A bigger revision will made after 22/04/2024.
My questions on this issue comments will also be discussed here. We've pretty much done our job for now!

**Comment by Mutti499** [comment]
From the #138 and #135  completely finished our requirements. It was a long road but it is ready for milestone 2. Lets goo!!!
