### ISSUE TITLE
Revise Elicitation Questions

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#113]
Quality elicitation questions are very important for quality requirements. That's why we need a quality team for this job. I think you are suitable for this task.Please try to turn the how based questions into what based questions in the light of the feedback given by the teacher.

Estimated Effort: 1 hour

Deadline: 07.03.2024

Reviewer : @baycici

**Comment by poyrazogluyigit** [comment]
@ceylingebes @Mutti499 It's been a very long while, but I've quickly gone over the questions to convert how? questions into what? questions:
https://hackmd.io/@nwangonulin/SJZ9RM9Z0/edit
It's not urgent, but please review this draft. When it's finalized, we can update the wiki page.

**Comment by Mutti499** [comment]
I really love seeing items in a grouped system. Good job mate!
