### ISSUE TITLE
Search Result Diagrams

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#114]
Diagrams help us understand the actual needs of the user, their actions and their needs while using our target software. Create all required diagrams related to searching.

* [x] Go over the lecture slides and make sure you understand how the diagrams should be created
* [x] Create a class diagram concerning searching and search results
* [x] Create a use case diagram connected to the class diagram above
* [x] Create a sequence diagram connected to the diagrams above
* [x] Discuss and correct with teammates

Deadline: 08.04.2024
Estimated effort: 4 hours

Reviewers: @Mutti499 @ErayEroglu

**Comment by Mutti499** [comment]
I look forward to your work as I expect the best from your team !

**Comment by kristinatrajkovski** [comment]
You may follow the progress at HackMD [here](https://hackmd.io/YdheLxICRxKK9ObnAn2L2g) . I am looking forward to your feedback.

**Comment by Mutti499** [comment]
Can we talk about your diagrams when you're free? It looks good but I need to ask a few question to understand clearly

**Comment by Mutti499** [comment]
We have talked with Kristina about their diagrams. For now, it looks really well. KEEP IT UP!

**Comment by kristinatrajkovski** [comment]
I am closing this issue for now as it has been approved by our reviewer :) Feel free to reopen if you see any problems.
