### ISSUE TITLE
Feed Diagrams

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#115]
Diagrams help us better implement the functions we want in our program. BuRoute's feed page is a very important page, so it should be implemented clearly. To achieve this we need well-designed diagrams.
Create all necessary diagrams related to the search.

* [x] Create a class diagram.
* [x] Create a use case diagram.
* [x] Create a sequence diagram which uses the use case diagram and class diagram.
* [x] Correct your implementation according to the feedback.

Deadline: 08.04.2024
Estimated effort: 3 hours

Reviewers: @kristinatrajkovski @halil-karabacak

**Comment by Mutti499** [comment]
We finished our diagrams but it absolutely needs a feedback! @kristinatrajkovski @halil-karabacak can you take look ?

**Comment by kristinatrajkovski** [comment]
I just took a look at your diagrams. I really like how you incorporated your teammates' work into your own part. Although our diagrams are truly large and getting larger, I really think they capture the design ideas for the feed as well.

I personally would not change a thing, so feel free to close the issue if you think it is ready as well.

**Comment by Mutti499** [comment]
Receiving a positive feedback from a quality teammate makes me happy. If the @halil-karabacak  is also satisfied with this task, I am considering moving on to the other task for now. Of course, it is enough for Kristiina to approve it, but I feel insecure about the sequence diagram I drew and I would like to know if there is a detail I missed that should be added.

**Comment by halil-karabacak** [comment]
Nice work!! Sorry for being late I had been a little overwhelmed by tasks. I had just found time and this seems pretty well. Good job!

**Comment by Mutti499** [comment]
It's okay, my friend. Thank you for your comments!
