### ISSUE TITLE
Profile Creation Diagrams

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#116]
Create the diagrams required for user interaction with profile systems.

* [x] Class diagram regarding profile creation and editing
* [x] Use case diagram in relation with the above diagram
* [x] Sequence diagram in relation with both diagrams above

Be sure to review and accommodate with respect to other diagrams.

* [x] Deadline: 09.04.2024 23.59

**Comment by Mutti499** [comment]
Guys while implementing feed diagrams, I also added some user functionality to make my diagram work. Can you take a look and implement over it wiithout deleting?

**Comment by poyrazogluyigit** [comment]
Done! We've also edited some of the user functionality you provided but it's not too much. Waiting for review by assigned reviewer and later the whole group.

**Comment by Mutti499** [comment]
Excellent job! I am impressed. @mehmeteminipekdal  can you make a final evaluation for them?

**Comment by baycici** [comment]
We have made the diagrams on time.
