### ISSUE TITLE
Login & Sign Up Diagrams

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#118]
Login and sign up pages are crucial to a functional application/website. To be able to implement it more accurately in future;  class, use case and sequence diagrams related to login and sign up functionalities should be designed.

- [x]  Create class diagrams for login & signup
- [x]  Create use case diagrams for login & signup
- [x]  Create sequence diagrams for login & signup

Deadline: 14.04.2024
Estimated effort: 2 hours

Reviewers: @berkaykeskino , @ahmetcicekk006

**Comment by ceylingebes** [comment]
@Taha-Topaloglu and I were actually completed this task on 10.04.2024 but it seems like we have overseen and completely forgot to update on this issue. Can you check the diagrams real quick and give a feedback so that we can close this issue 🥺🥺🥺 @berkaykeskino @ahmetcicekk006 sorry for this huge inconvenience and delay.

**Comment by ahmetcicekk006** [comment]
It seems nice to me.Well done!

**Comment by berkaykeskino** [comment]
Nice job!

**Comment by ceylingebes** [comment]
Thanks a lot for the feedback @ahmetcicekk006 @berkaykeskino :) Now closing this issue as completed ✅
