### ISSUE TITLE
[Kristina, Mutti] Web Back End - Django, API and Databases

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#120]
We will be working on Web Back End at least for the week of April 15th. The important thing is to fully understand what features our requested API can and should provide, research the allowed environment which includes Django, and create at least a minor prototype of the API itself.

- [x] Research Django
- [x] Research Wikidata and its Queries
- [x] Create an example API

Deadline: Tuesday, April 16th
Estimated effort: 3-4 hours

Reviewers: @ceylingebes @Taha-Topaloglu

**Comment by kristinatrajkovski** [comment]
I have created a query in SPARQL which retrieves title, description, longitude, and latitude of some locations in Istanbul (note that we definitely need much more information). I have also integrated it into a django project just to see how it would work. Please check 26c58aa for the current results.

**Comment by kristinatrajkovski** [comment]
Very large update can be seen at 3dc83eb18d58a95e22caa20dfa28d8019b3cb2c4 . Now we can make single-word searches and display various data (name, description, coordinates, inception, 5 nearby places, 5 places from the same period).

**Comment by Mutti499** [comment]
- New fields named image url and Wikipedia article link added to return values. 
- New filter added according to the style of the architecture.
- Private database searches are implemented according to the class diagrams

Last 2 features need improvement and testing

**Comment by Mutti499** [comment]
We have some problems:
- Null checker needs to be added 
- We are getting error in .../results/... sub url needs to be fixed immediately

**Comment by Mutti499** [comment]
Problems solved and pull request is opened. Waiting review from our friends.

Last commit: [7e374c2](https://github.com/bounswe/bounswe2024group9/commit/7e374c22f2ad47b7a0083b832a605a84ff0395b0)

**Comment by poyrazogluyigit** [comment]
Does the API return a fixed number of results? Been trying with different inputs and I always get (at most) 10 results.

**Comment by kristinatrajkovski** [comment]
Yes the current limit is set as 10. When makig the API I just thought that would be a reasonable amount of choices we can offer to a user. If you want to decrease or increase that number for any reason let us know.

**Comment by kristinatrajkovski** [comment]
Closing as it is considered done after reviewer comments and the pull request merged. Will open other issues as necessary.
