### ISSUE TITLE
[Halil] Mobile Backend - Prepare a simple demo to team members connecting Django REST to React Native

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#121]
We will be working on Web Back End at least for the week of April 15th. The important thing is to fully understand what features our requested API can and should provide, research the allowed environment which includes Django, and create at least a minor prototype of the API itself.

- [X]  Research React Native and prepare the development environment
- [x] Research Wikidata and its Queries
- [X]  Start Working on the mysql with simple table such as user
- [x] Create an example API that connects front-end to database
- [x] Research on the files to be shared over github for both API and mobile front-end. Write .env, .gitignore files accordingly.
Deadline: Tuesday, April 16th
Estimated effort: 4 hours

Notify: @ceylingebes @Taha-Topaloglu @poyrazogluyigit @berkaykeskino

**Comment by halil-karabacak** [comment]
Installed necessary frameworks and set the development environment. Currently a simple mobile front-end working with React Native is functional and connected to a mysql databse over Django REST API. Will open a branch.
![image](https://github.com/bounswe/bounswe2024group9/assets/73756179/baa08feb-74db-4004-b245-2edd7a7b9694)

**Comment by Mutti499** [comment]
Oh may god! The man literally uplaoded an image about an issue. Which level is that!? If I were Teacher Suzan, I would give a direct AA.

What do you think ? @kristinatrajkovski 

![image](https://github.com/bounswe/bounswe2024group9/assets/75087023/930066f0-92a9-418c-9a60-752277b3c24e)

**Comment by halil-karabacak** [comment]
Pushed the initial version of mobile app to the branch [mobile/dev](https://github.com/bounswe/bounswe2024group9/tree/mobile/dev) in commit [#f42bb3e](https://github.com/bounswe/bounswe2024group9/commit/f42bb3efee3387d74515135a1cc0538e6ba4bf6d). We will now continue with syncing with web-backend team & and looking forward to implement pages.

**Comment by halil-karabacak** [comment]
> Oh may god! The man literally uplaoded an image about an issue. Which level is that!? If I were Teacher Suzan, I would give a direct AA.
> 
> What do you think ? @kristinatrajkovski
> 
> ![image](https://private-user-images.githubusercontent.com/75087023/322996831-930066f0-92a9-418c-9a60-752277b3c24e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjkxMjgsIm5iZiI6MTcxMzM2ODgyOCwicGF0aCI6Ii83NTA4NzAyMy8zMjI5OTY4MzEtOTMwMDY2ZjAtOTJhOS00MThjLTlhNjAtNzUyMjc3YjNjMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNDljZmMyMzBkODlmYzgyNWU5NmM3MWFlNDJlN2M4YzcxOGU2ZjMzNGJiNmM1YjdmN2Q1NmNmMTk1ZTUzZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foDPaCZu4kTV_ZjN1vSq_4IN-CB7F3QGyzLDlwUCd0o)

I am just following the path you have created for us mutti.
