### ISSUE TITLE
Add More Information to the Official Plan

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#125]
From the feedback in Milestone 1, it was pointed out that plan entries in Project Libre need to be elaborated (do not just say implement project). Now that we know more about the milestones as well, the plan can be more realistic and detailed. Make sure to include both personal and imposed milestones.

Deadline: 19.04.2024
Estimated effort: 30mins
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
I can help with your task if you want. Just let me know!

**Comment by kristinatrajkovski** [comment]
@Mutti499 Thank you so much for offering. 

I have made some changes, you can see them [here](https://github.com/bounswe/bounswe2024group9/blob/main/CMPE352%20Group%209.pod) or from the related pdf file [here](https://github.com/bounswe/bounswe2024group9/wiki/Long%E2%80%90term-planning-%F0%9F%93%85).

If you have some minor corrections please feel free to do them yourself, and I am always happy to discuss more about larger changes.

**Comment by Mutti499** [comment]
It seems a lot better mate. Thank you, you did a great job!

**Comment by Mutti499** [comment]
I am closing this issue for now!
