### ISSUE TITLE
[Halil, Yiğit Kağan] Implement Search Result page for mobile

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#127]
#### Implementing a functional Search Result page that is in line with the [mockup](https://github.com/bounswe/bounswe2024group9/wiki/Mockups#mobile-2). Functionality is not first priority at the moment because, there are updates on search mechanism. 

* A Search Bar
* A section showing wikidata api result with an image
* Routes may be shown as well after the upper section.

* [21/04/2024] Deadline

**Comment by halil-karabacak** [comment]
We created the [branch](https://github.com/bounswe/bounswe2024group9/tree/mobile/search_result) in which we will develop the search result page.

**Comment by poyrazogluyigit** [comment]
I will be documenting my design decisions as I develop my part.
* Search results will clear when search bar is empty

**Comment by poyrazogluyigit** [comment]
I've installed react-navigation/native, but I'm not sure whether this change reflects on the whole project. I will implement page change with this. Take note.

**Comment by halil-karabacak** [comment]
You are right, but at this point we need 2 pages imo. Please take a brief look at my last [commit ](https://github.com/bounswe/bounswe2024group9/commit/9b488bd0b8ff361d1c7b24223dc7baf65eb3825f)which handles 2 pages along with App.tsx. Currently this page gives a brief description of selected item & a small image. Front-end could be definitely improved and we may need to discuss some performance of wikidataAPI results with the mutti & kristina.

**Comment by halil-karabacak** [comment]
It seems we have now completed the initial version of the search result after my last commit e021f9d. To continue further, we need to pull backend completely.
