### ISSUE TITLE
[Eray,Mutti] Discuss the API Use on the Frontend

### ISSUE THREAD

**Issue by ErayEroglu** [bounswe/bounswe2024group9#130]
* Due to the request of frontend members, there will be discussion about how to use the api on the web search result page.
* The main focus will be the usage of api, design part will be discussed later if necessary

 
*  Deadline: 21.04.2024

**Comment by Mutti499** [comment]
We discussed and we found out that we need to move our implementation to the remote server. For now I am searching AWS MYSQL database and Heroku. I will update here with new features!

**Comment by ErayEroglu** [comment]
@kristinatrajkovski also joined the discussion as a member of backend member, thanks for the contribution.

**Comment by ErayEroglu** [comment]
I think the api works greatly and everybody understood how to use it. See you on another task @Mutti499
