### ISSUE TITLE
[Berkay] Implement Sign up page for mobile

### ISSUE THREAD

**Issue by berkaykeskino** [bounswe/bounswe2024group9#132]
Implement the mock up for sign up. It doesn't need to involve "Sign Up with Google" yet. It should involve navigating to the login page.

Deadline: 21.04.2024

Reviewers: @halil-karabacak @ceylingebes

**Comment by Mutti499** [comment]
Hey mate @berkaykeskino how is this task going?

**Comment by berkaykeskino** [comment]
Hey! It is done now. Thanks to @halil-karabacak for helping me with the connection to backend

**Comment by halil-karabacak** [comment]
Good job Berkay, it works as intended. We'll pull your code today. Thanks!
