### ISSUE TITLE
[Ahmet Burak,Ozgur] Functionalities of login and sign up pages

### ISSUE THREAD

**Issue by baycici** [bounswe/bounswe2024group9#133]
* Connect the pages to the api

* [x] Deadline:21/04/2024

**Comment by baycici** [comment]
Because of the lack of knowledge about the database we decided to ask the group in the meeting about the method we will take and continue afterwards.

**Comment by Mutti499** [comment]
We talked with @baycici , I will help them complete the integration with the backend!

**Comment by Mutti499** [comment]
Me and @kristinatrajkovski also involved in this task and completed the missing backend parts. Good job you all

**Comment by kristinatrajkovski** [comment]
Completed and merged [here](https://github.com/bounswe/bounswe2024group9/pull/151). Closing this issue as complete.
