### ISSUE TITLE
[Web team] Revise System Requirements

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#135]
Make sure that the system requirements do not contain any of the user requirements. Add some security and safety requirements. Think of other things to list if necessary. 

Deadline: 25.04.2024
Estimated effort: 1 hour
Reviewer: @halil-karabacak

**Comment by Mutti499** [comment]
Let's start it!

**Comment by Mutti499** [comment]
Taking inspiration from feedback notes with Kristina:

- We separated what should be in user requirements from system requirements.
- We added KVKK rules under the security heading.
- We added articles that provide information about using semantic search and wikidata.
- We made the overall image consistent
- We deleted unnecessary items that needed to be changed.
- We updated the glossary to be consistent.

**Comment by Mutti499** [comment]
@halil-karabacak we know you are tired. But we need your opinion and review!

![sl15jp621j851](https://github.com/bounswe/bounswe2024group9/assets/75087023/ccaf046f-a434-44fa-9d70-7dc9dca7a756)

**Comment by ErayEroglu** [comment]
Even though we miss the deadline a little bit, I think we did a great job. This was important and done now, good job everyone

**Comment by halil-karabacak** [comment]
Ahhh, missed the notification sorry. Seems really fine, good job
