### ISSUE TITLE
[Mutti] Revise scenarios

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#136]
Add more description to the scenarios. Make sure the persona is well defined. Make sure that the scenarios are well aligned with our requirements. 

Deadline: 25.04.2024
Estimated effort: 1hr
Reviewer: @kristinatrajkovski

**Comment by Mutti499** [comment]
I've added a _Subjects_ section to all scenarios, which gives some insight into the characters in the story, and I've now detailed them so they look better.

I had help on the journey from my old friend GPT, not gona lie!

![image](https://github.com/bounswe/bounswe2024group9/assets/75087023/617e111a-a5c6-461c-ba17-3e67b5dda6ee)

**Comment by kristinatrajkovski** [comment]
I think it looks great! The subjects give more insight of the persona and why he/she is using our application. As your reviewer I am closing this issue as complete.

P.S. Are you really sure Chat GPT is your friend? With that much interaction and information sharing, I would be scared if I were you :)
