### ISSUE TITLE
[Mutti] Revise Search Mockups

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#137]
Add more information to our search results in the mockups. Make sure to add the nearby places and other links we dicussed to the search results. Please add this information both to mobile and web. Make sure our requirements are aligned with the mockups.  

Deadline: 25.04.2024.
Estimated effort: 1hr
Reviewer: @kristinatrajkovski

**Comment by Mutti499** [comment]
New search result mockups are ready for mobile and web. I am uploading them right now.
I am the best Figma developer in the world!

![figma](https://github.com/bounswe/bounswe2024group9/assets/75087023/4c24c593-2f1a-4893-a811-09624c137240)

**Comment by kristinatrajkovski** [comment]
Good job to the best "figmacı" I know. Your mockups really represent our ideas and goals. Thanks for the very much needed update!
