### ISSUE TITLE
[Mobile Team] Revise User Requirements

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#138]
Please revise the user requirements according to the feedback we received from milestone 1. Make sure to include your changes at [this](https://hackmd.io/x-KvUXF7TK-3TCnwKE44cw?both) HackMD file first. Make sure to add the missing logical pieces (log out, delete route, delete profile, etc.), to erase the different user types as agreed at the feedback meeting, and that the form of the user requirements begins with "user shall/should".

 Deadline: 25.04.2024.
Estimated effort: 1 hour
Reviewer: @Mutti499

**Comment by kristinatrajkovski** [comment]
Please revise the whole section "##### 1.1.3.2 **Route Options**". None of the requirements are written as true user requirements IMO.

Also take #111 as a reference. Some work has been already done by @halil-karabacak and @Mutti499 (YAY!)

**Comment by halil-karabacak** [comment]
@halil-karabacak @poyrazogluyigit @berkaykeskino @ceylingebes @Taha-Topaloglu I hope you have seen this issue.

**Comment by Mutti499** [comment]
Be carefull folks, it is not an easy task!

**Comment by halil-karabacak** [comment]
It seems no one really looks here which makes this issue completely meaningless. I will do all work now, remove other assignees.

**Comment by kristinatrajkovski** [comment]
I'm sorry to see this happen. While I do have a lot of my own tasks, I would be happy to review and help out, just let me know if necessary

**Comment by halil-karabacak** [comment]
> I'm sorry to see this happen. While I do have a lot of my own tasks, I would be happy to review and help out, just let me know if necessary

I know the heavy work you're doing, so thanks a lot. I guess I can handle, appreciated

**Comment by kristinatrajkovski** [comment]
Our assigned deadline was today. It is not an easy task and that is why it was assigned to half of the group. We have been discussing this for weeks now, and not getting input or any signs of any progress from any of you was definitely an alarm that we should do something different. You should not be seeing the milestone as the only deadline anyways. You should be aware that there is only a few people in this group doing the whole work, so a decision to take on even more load is never easy and probably wasn't for Halil either. 

If you are eager to help out I believe you can still pitch in, but when you are not I don't think you should get mad and hostile when someone else just wants to get the job done.

**Comment by ErayEroglu** [comment]
I finished my other tasks so I am available and can help Halil.

**Comment by Mutti499** [comment]
I'm free too. Halil, can you reach us bro

**Comment by ErayEroglu** [comment]
@ceylingebes and I added some terms to the glossaray and examined the requirements. Also we found some duplicate or similar requirements, and elimanated one of the duplicates considerig the subtitle of that requirement. We added them to wiki pages, you can revise and give feedback to us. If there are things that needed to be edited, you can inform us

**Comment by ceylingebes** [comment]
You can check our work regarding Glossary from [here](https://github.com/bounswe/bounswe2024group9/wiki/Glossary) and Requirements from [here](https://github.com/bounswe/bounswe2024group9/wiki/Requirements).

**Comment by Mutti499** [comment]
Great job people! This task was harder than implementation and I am so proud.

**Comment by ErayEroglu** [comment]
@Mutti499, what do you think about the last form of the both requirements and glossary? If you think they are okay, we can close the issue. Otherwise, please inform us about the parts needing an edit

**Comment by Mutti499** [comment]
I think it looks great. I am closing this with #111. We really learned our lessons from first milestone!
