### ISSUE TITLE
[Kristina, Eray] Revise Design Diagrams

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#144]
From the feedback from the assistant and some of our own we should:
* [x] Create a more abstract class for page management
* [x] Complete the User class
* [x] Profile Controller should be connected to the user
* [x] Try to match names of classes with the code (discuss which one should be changed)

Deadline: 27.04.2024
Estimated effort: 2hrs
Reviewer: @Mutti499

**Comment by ErayEroglu** [comment]
I have some other tasks to handle, after finishing them I will start working on this

**Comment by Mutti499** [comment]
I think its time for a review your tasks. I will revise them today!

**Comment by Mutti499** [comment]
I revised and informed my friends. It was really good looking and ready for implementation! WAY TO GOOO!!

**Comment by kristinatrajkovski** [comment]
After nice feedback from both our reviewer and the assistant, I am closing this issue. Way to gooo!
