### ISSUE TITLE
Deployment Testing

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#145]
## Description
First version of the deployment is done and works on my system. I need people to test it on their systems before tomorrow's meeting.

## Prerequisites
Make sure that docker and docker compose are installed on your system. You can check by typing 
> docker
docker-compose

on your terminals. If they are not installed, you can simply download docker desktop.

## What you need to do:
* pull/switch to docker branch
* run: 
> docker compose build
docker compose up

after this, the web page should be accessible on port 3000.

If you encounter any errors, do not try to fix them; simply report them here. While reporting, please describe as verbosely as possible (full output logs/screenshots are a good way). 

## Deadline:
27.04.2024 12.00 PM

**Comment by poyrazogluyigit** [comment]
You do not need to spare time from other tasks to do the testing. It would suffice if someone available tried before tomorrow noon.

**Comment by kristinatrajkovski** [comment]
I tried running it according to your descriptions and encountered an error. I am pasting the whole log (sorry for the length)
[+] Building 511.9s (11/17)                                                                                                                       docker:default
 => [web internal] load build definition from Dockerfile                                                                                                    0.1s
 => => transferring dockerfile: 137B                                                                                                                        0.0s 
 => [web internal] load .dockerignore                                                                                                                       0.1s 
 => => transferring context: 2B                                                                                                                             0.0s 
 => [db internal] load .dockerignore                                                                                                                        0.1s 
 => => transferring context: 2B                                                                                                                             0.0s 
 => [db internal] load build definition from Dockerfile                                                                                                     0.1s 
 => => transferring dockerfile: 419B                                                                                                                        0.0s 
 => [web internal] load metadata for docker.io/library/node:20                                                                                              4.3s
 => [db internal] load metadata for docker.io/library/python:3.11-slim                                                                                      4.6s
 => CANCELED [web 1/4] FROM docker.io/library/node:20@sha256:3864be2201676a715cf240cfc17aec1d62459f92a7cbe7d32d1675e226e736c9                             507.4s
 => => resolve docker.io/library/node:20@sha256:3864be2201676a715cf240cfc17aec1d62459f92a7cbe7d32d1675e226e736c9                                            0.0s
 => => sha256:3864be2201676a715cf240cfc17aec1d62459f92a7cbe7d32d1675e226e736c9 1.21kB / 1.21kB                                                              0.0s
 => => sha256:740804d1d9a2a05282a7a359446398ec5f233eea431824dd42f7ba452fa5ab98 2.00kB / 2.00kB                                                              0.0s
 => => sha256:b39e0b4385dc35a8bdfde21a5c66250ad72b2602c4af44e43ae9af12d0b1cfd7 7.41kB / 7.41kB                                                              0.0s
 => => sha256:1468e7ff95fcb865fbc4dee7094f8b99c4dcddd6eb2180cf044c7396baf6fc2f 49.58MB / 49.58MB                                                          167.4s
 => => sha256:2cf9c2b42f41b1845f3e4421b723d56146db82939dc884555e077768e18132f4 24.05MB / 24.05MB                                                          132.2s 
 => => sha256:c4c40c3e3cdf945721f480e1d939aac857876fdb5c33b8fbfcf655c63b0b9428 64.14MB / 64.14MB                                                          212.7s 
 => => sha256:c05cc1123d7e335d59b0f465c23b7ad2ad27f4875b6c3eab41c65a9b50efa382 18.87MB / 211.18MB                                                         507.4s 
 => => sha256:04f2356c02d21ef160986f7994210be28dab889b9ba0724e126bd2ee4ed21cd6 3.37kB / 3.37kB                                                            168.3s 
 => => extracting sha256:1468e7ff95fcb865fbc4dee7094f8b99c4dcddd6eb2180cf044c7396baf6fc2f                                                                   5.7s 
 => => sha256:0d0c50523b913bafd5bd2633ede982f69c0e3efea5a3b53f89122d6a82e94dcd 48.02MB / 48.02MB                                                          234.9s 
 => => extracting sha256:2cf9c2b42f41b1845f3e4421b723d56146db82939dc884555e077768e18132f4                                                                   1.6s 
 => => extracting sha256:c4c40c3e3cdf945721f480e1d939aac857876fdb5c33b8fbfcf655c63b0b9428                                                                   9.7s 
 => => sha256:d82ea00ba3b4e489db5a7e199a5d99778596b0272c8f7b7c0b783c47155acdc8 1.25MB / 1.25MB                                                            221.7s 
 => => sha256:e61adbe39f6613cc222b7d3f12aac1cfc0f30fa1cdc42b26234151af17c7e2d5 452B / 452B                                                                222.6s 
 => [web internal] load build context                                                                                                                       0.2s 
 => => transferring context: 805.19kB                                                                                                                       0.1s 
 => [db 1/5] FROM docker.io/library/python:3.11-slim@sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c                              403.2s 
 => => resolve docker.io/library/python:3.11-slim@sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c                                   0.0s 
 => => sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c 1.65kB / 1.65kB                                                              0.0s 
 => => sha256:c1871384ae32a849812b9873f3358328b583bcf69c5ff6e5575b023af3651bbf 1.37kB / 1.37kB                                                              0.0s 
 => => sha256:d844b89b8a09422556582f4ec94e4b9b37a5e429d6552b8140b211dea0e4ad31 6.92kB / 6.92kB                                                              0.0s 
 => => sha256:b0a0cf830b12453b7e15359a804215a7bcccd3788e2bcecff2a03af64bbd4df7 29.15MB / 29.15MB                                                          395.4s 
 => => sha256:72914424168c8ebb0dbb3d0e08eb1d3b5b2a64cc51745bd65caf29c335b31dc7 3.51MB / 3.51MB                                                            247.7s
 => => sha256:d12a047f1c7ea4f8e51322323d769a331c46fbf44d958ccce3359a6bd932f3d1 12.87MB / 12.87MB                                                          260.5s 
 => => sha256:ab33f1a2f6621fe008081cae7c61b1ac6343eecd65c7de7345642cc73d4e18eb 244B / 244B                                                                261.5s 
 => => sha256:94510a1366bcf144be79366b3176ae5866b43db71c3d3818e3d56e2e19df964b 3.41MB / 3.41MB                                                            265.9s 
 => => extracting sha256:b0a0cf830b12453b7e15359a804215a7bcccd3788e2bcecff2a03af64bbd4df7                                                                   4.1s 
 => => extracting sha256:72914424168c8ebb0dbb3d0e08eb1d3b5b2a64cc51745bd65caf29c335b31dc7                                                                   0.4s 
 => => extracting sha256:d12a047f1c7ea4f8e51322323d769a331c46fbf44d958ccce3359a6bd932f3d1                                                                   1.5s 
 => => extracting sha256:ab33f1a2f6621fe008081cae7c61b1ac6343eecd65c7de7345642cc73d4e18eb                                                                   0.0s 
 => => extracting sha256:94510a1366bcf144be79366b3176ae5866b43db71c3d3818e3d56e2e19df964b                                                                   0.9s 
 => [db internal] load build context                                                                                                                        0.1s 
 => => transferring context: 173.07kB                                                                                                                       0.0s 
 => ERROR [db 2/5] RUN apt-get update  && apt-get install -y --no-install-recommends  git  pkg-config  default-libmysqlclient-dev  gcc  && rm -rf /var/l  103.8s 
------
 > [db 2/5] RUN apt-get update  && apt-get install -y --no-install-recommends   git     pkg-config      default-libmysqlclient-dev      gcc     && rm -rf /var/lib/apt/lists/*:
1.360 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
1.599 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
1.741 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
1.878 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
9.726 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
9.848 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [155 kB]
11.59 Fetched 9209 kB in 11s (872 kB/s)
11.59 Reading package lists...
12.80 Reading package lists...
13.83 Building dependency tree...
14.10 Reading state information...
14.68 The following additional packages will be installed:
14.68   binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-12 gcc-12 git-man
14.69   libasan8 libatomic1 libbinutils libbrotli1 libc-dev-bin libc6-dev libcc1-0
14.69   libcrypt-dev libctf-nobfd0 libctf0 libcurl3-gnutls liberror-perl
14.69   libgcc-12-dev libgdbm-compat4 libgomp1 libgprofng0 libisl23 libitm1
14.69   libjansson4 libldap-2.5-0 liblsan0 libmariadb-dev libmariadb-dev-compat
14.69   libmariadb3 libmpc3 libmpfr6 libnghttp2-14 libnsl-dev libperl5.36
14.69   libpkgconf3 libpsl5 libquadmath0 librtmp1 libsasl2-2 libsasl2-modules-db
14.69   libssh2-1 libssl-dev libtirpc-dev libtsan2 libubsan1 linux-libc-dev
14.69   mariadb-common mysql-common perl perl-modules-5.36 pkgconf pkgconf-bin
14.69   rpcsvc-proto zlib1g-dev
14.70 Suggested packages:
14.70   binutils-doc cpp-doc gcc-12-locales cpp-12-doc gcc-multilib make
14.70   manpages-dev autoconf automake libtool flex bison gdb gcc-doc
14.70   gcc-12-multilib gcc-12-doc gettext-base git-daemon-run | git-daemon-sysvinit
14.70   git-doc git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
14.70   glibc-doc sensible-utils libssl-doc perl-doc libterm-readline-gnu-perl
14.70   | libterm-readline-perl-perl libtap-harness-archive-perl
14.70 Recommended packages:
14.70   patch less ssh-client manpages manpages-dev libc-devtools libldap-common
14.70   publicsuffix libsasl2-modules
15.37 The following NEW packages will be installed:
15.37   binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-12
15.37   default-libmysqlclient-dev gcc gcc-12 git git-man libasan8 libatomic1
15.37   libbinutils libbrotli1 libc-dev-bin libc6-dev libcc1-0 libcrypt-dev
15.37   libctf-nobfd0 libctf0 libcurl3-gnutls liberror-perl libgcc-12-dev
15.37   libgdbm-compat4 libgomp1 libgprofng0 libisl23 libitm1 libjansson4
15.37   libldap-2.5-0 liblsan0 libmariadb-dev libmariadb-dev-compat libmariadb3
15.37   libmpc3 libmpfr6 libnghttp2-14 libnsl-dev libperl5.36 libpkgconf3 libpsl5
15.38   libquadmath0 librtmp1 libsasl2-2 libsasl2-modules-db libssh2-1 libssl-dev
15.38   libtirpc-dev libtsan2 libubsan1 linux-libc-dev mariadb-common mysql-common
15.38   perl perl-modules-5.36 pkg-config pkgconf pkgconf-bin rpcsvc-proto
15.38   zlib1g-dev
15.55 0 upgraded, 60 newly installed, 0 to remove and 0 not upgraded.
15.55 Need to get 72.1 MB of archives.
15.55 After this operation, 317 MB of additional disk space will be used.
15.55 Get:1 http://deb.debian.org/debian bookworm/main amd64 perl-modules-5.36 all 5.36.0-7+deb12u1 [2815 kB]
18.35 Get:2 http://deb.debian.org/debian bookworm/main amd64 libgdbm-compat4 amd64 1.23-3 [48.2 kB]
18.47 Get:3 http://deb.debian.org/debian bookworm/main amd64 libperl5.36 amd64 5.36.0-7+deb12u1 [4218 kB]
20.77 Get:4 http://deb.debian.org/debian bookworm/main amd64 perl amd64 5.36.0-7+deb12u1 [239 kB]
20.95 Get:5 http://deb.debian.org/debian bookworm/main amd64 binutils-common amd64 2.40-2 [2487 kB]
22.26 Get:6 http://deb.debian.org/debian bookworm/main amd64 libbinutils amd64 2.40-2 [572 kB]
22.60 Get:7 http://deb.debian.org/debian bookworm/main amd64 libctf-nobfd0 amd64 2.40-2 [153 kB]
22.76 Get:8 http://deb.debian.org/debian bookworm/main amd64 libctf0 amd64 2.40-2 [89.8 kB]
22.87 Get:9 http://deb.debian.org/debian bookworm/main amd64 libgprofng0 amd64 2.40-2 [812 kB]
23.25 Get:10 http://deb.debian.org/debian bookworm/main amd64 libjansson4 amd64 2.14-2 [40.8 kB]
23.35 Get:11 http://deb.debian.org/debian bookworm/main amd64 binutils-x86-64-linux-gnu amd64 2.40-2 [2246 kB]
24.26 Get:12 http://deb.debian.org/debian bookworm/main amd64 binutils amd64 2.40-2 [65.0 kB]
24.37 Get:13 http://deb.debian.org/debian bookworm/main amd64 libisl23 amd64 0.25-1.1 [683 kB]
24.74 Get:14 http://deb.debian.org/debian bookworm/main amd64 libmpfr6 amd64 4.2.0-1 [701 kB]
25.08 Get:15 http://deb.debian.org/debian bookworm/main amd64 libmpc3 amd64 1.3.1-1 [51.5 kB]
25.20 Get:16 http://deb.debian.org/debian bookworm/main amd64 cpp-12 amd64 12.2.0-14 [9764 kB]
31.82 Get:17 http://deb.debian.org/debian bookworm/main amd64 cpp amd64 4:12.2.0-3 [6836 B]
31.93 Get:18 http://deb.debian.org/debian bookworm/main amd64 mysql-common all 5.8+1.1.0 [6636 B]
32.03 Get:19 http://deb.debian.org/debian bookworm/main amd64 mariadb-common all 1:10.11.6-0+deb12u1 [24.4 kB]
32.13 Get:20 http://deb.debian.org/debian bookworm/main amd64 libmariadb3 amd64 1:10.11.6-0+deb12u1 [174 kB]
32.31 Get:21 http://deb.debian.org/debian bookworm/main amd64 libssl-dev amd64 3.0.11-1~deb12u2 [2430 kB]
35.98 Get:22 http://deb.debian.org/debian-security bookworm-security/main amd64 libc-dev-bin amd64 2.36-9+deb12u6 [45.6 kB]
36.12 Get:23 http://deb.debian.org/debian-security bookworm-security/main amd64 linux-libc-dev amd64 6.1.85-1 [1968 kB]
37.13 Get:24 http://deb.debian.org/debian bookworm/main amd64 libcrypt-dev amd64 1:4.4.33-2 [118 kB]
37.27 Get:25 http://deb.debian.org/debian bookworm/main amd64 libtirpc-dev amd64 1.3.3+ds-1 [191 kB]
37.45 Get:26 http://deb.debian.org/debian bookworm/main amd64 libnsl-dev amd64 1.3.0-2 [66.4 kB]
37.66 Get:27 http://deb.debian.org/debian bookworm/main amd64 rpcsvc-proto amd64 1.4.3-1 [63.3 kB]
37.78 Get:28 http://deb.debian.org/debian-security bookworm-security/main amd64 libc6-dev amd64 2.36-9+deb12u6 [1902 kB]
39.06 Get:29 http://deb.debian.org/debian bookworm/main amd64 zlib1g-dev amd64 1:1.2.13.dfsg-1 [916 kB]
39.60 Get:30 http://deb.debian.org/debian bookworm/main amd64 libmariadb-dev amd64 1:10.11.6-0+deb12u1 [265 kB]
39.87 Get:31 http://deb.debian.org/debian bookworm/main amd64 libmariadb-dev-compat amd64 1:10.11.6-0+deb12u1 [23.2 kB]
39.99 Get:32 http://deb.debian.org/debian bookworm/main amd64 default-libmysqlclient-dev amd64 1.1.0 [3092 B]
40.09 Get:33 http://deb.debian.org/debian bookworm/main amd64 libcc1-0 amd64 12.2.0-14 [41.7 kB]
40.21 Get:34 http://deb.debian.org/debian bookworm/main amd64 libgomp1 amd64 12.2.0-14 [116 kB]
40.35 Get:35 http://deb.debian.org/debian bookworm/main amd64 libitm1 amd64 12.2.0-14 [26.1 kB]
40.51 Get:36 http://deb.debian.org/debian bookworm/main amd64 libatomic1 amd64 12.2.0-14 [9328 B]
40.62 Get:37 http://deb.debian.org/debian bookworm/main amd64 libasan8 amd64 12.2.0-14 [2195 kB]
43.06 Get:38 http://deb.debian.org/debian bookworm/main amd64 liblsan0 amd64 12.2.0-14 [969 kB]
43.83 Get:39 http://deb.debian.org/debian bookworm/main amd64 libtsan2 amd64 12.2.0-14 [2196 kB]
45.53 Get:40 http://deb.debian.org/debian bookworm/main amd64 libubsan1 amd64 12.2.0-14 [883 kB]
46.40 Get:41 http://deb.debian.org/debian bookworm/main amd64 libquadmath0 amd64 12.2.0-14 [144 kB]
46.56 Get:42 http://deb.debian.org/debian bookworm/main amd64 libgcc-12-dev amd64 12.2.0-14 [2437 kB]
48.03 Get:43 http://deb.debian.org/debian bookworm/main amd64 gcc-12 amd64 12.2.0-14 [19.3 MB]
63.93 Get:44 http://deb.debian.org/debian bookworm/main amd64 gcc amd64 4:12.2.0-3 [5216 B]
64.03 Get:45 http://deb.debian.org/debian bookworm/main amd64 libbrotli1 amd64 1.0.9-2+b6 [275 kB]
64.24 Get:46 http://deb.debian.org/debian bookworm/main amd64 libsasl2-modules-db amd64 2.1.28+dfsg-10 [20.3 kB]
64.33 Get:47 http://deb.debian.org/debian bookworm/main amd64 libsasl2-2 amd64 2.1.28+dfsg-10 [59.7 kB]
64.44 Get:48 http://deb.debian.org/debian bookworm/main amd64 libldap-2.5-0 amd64 2.5.13+dfsg-5 [183 kB]
64.63 Get:49 http://deb.debian.org/debian bookworm/main amd64 libnghttp2-14 amd64 1.52.0-1+deb12u1 [72.4 kB]
64.76 Get:50 http://deb.debian.org/debian bookworm/main amd64 libpsl5 amd64 0.21.2-1 [58.7 kB]
64.87 Get:51 http://deb.debian.org/debian bookworm/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2+b2 [60.8 kB]
64.98 Get:52 http://deb.debian.org/debian bookworm/main amd64 libssh2-1 amd64 1.10.0-3+b1 [179 kB]
65.15 Get:53 http://deb.debian.org/debian bookworm/main amd64 libcurl3-gnutls amd64 7.88.1-10+deb12u5 [385 kB]
66.33 Get:54 http://deb.debian.org/debian bookworm/main amd64 liberror-perl all 0.17029-2 [29.0 kB]
96.75 Ign:55 http://deb.debian.org/debian bookworm/main amd64 git-man all 1:2.39.2-1.1
96.75 Ign:56 http://deb.debian.org/debian bookworm/main amd64 git amd64 1:2.39.2-1.1
96.75 Ign:57 http://deb.debian.org/debian bookworm/main amd64 libpkgconf3 amd64 1.8.1-1
96.75 Ign:58 http://deb.debian.org/debian bookworm/main amd64 pkgconf-bin amd64 1.8.1-1
96.75 Ign:59 http://deb.debian.org/debian bookworm/main amd64 pkgconf amd64 1.8.1-1
96.76 Ign:60 http://deb.debian.org/debian bookworm/main amd64 pkg-config amd64 1.8.1-1
97.76 Ign:55 http://deb.debian.org/debian bookworm/main amd64 git-man all 1:2.39.2-1.1
97.76 Ign:56 http://deb.debian.org/debian bookworm/main amd64 git amd64 1:2.39.2-1.1
97.76 Ign:57 http://deb.debian.org/debian bookworm/main amd64 libpkgconf3 amd64 1.8.1-1
97.76 Ign:58 http://deb.debian.org/debian bookworm/main amd64 pkgconf-bin amd64 1.8.1-1
97.76 Ign:59 http://deb.debian.org/debian bookworm/main amd64 pkgconf amd64 1.8.1-1
97.76 Ign:60 http://deb.debian.org/debian bookworm/main amd64 pkg-config amd64 1.8.1-1
99.76 Ign:55 http://deb.debian.org/debian bookworm/main amd64 git-man all 1:2.39.2-1.1
99.76 Ign:56 http://deb.debian.org/debian bookworm/main amd64 git amd64 1:2.39.2-1.1
99.76 Ign:57 http://deb.debian.org/debian bookworm/main amd64 libpkgconf3 amd64 1.8.1-1
99.76 Ign:58 http://deb.debian.org/debian bookworm/main amd64 pkgconf-bin amd64 1.8.1-1
99.76 Ign:59 http://deb.debian.org/debian bookworm/main amd64 pkgconf amd64 1.8.1-1
99.76 Ign:60 http://deb.debian.org/debian bookworm/main amd64 pkg-config amd64 1.8.1-1
103.8 Err:55 http://deb.debian.org/debian bookworm/main amd64 git-man all 1:2.39.2-1.1
103.8   Could not connect to debian.map.fastlydns.net:80 (146.75.2.132), connection timed out Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]    
103.8 Err:56 http://deb.debian.org/debian bookworm/main amd64 git amd64 1:2.39.2-1.1
103.8   Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 Err:57 http://deb.debian.org/debian bookworm/main amd64 libpkgconf3 amd64 1.8.1-1
103.8   Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 Err:58 http://deb.debian.org/debian bookworm/main amd64 pkgconf-bin amd64 1.8.1-1
103.8   Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 Err:59 http://deb.debian.org/debian bookworm/main amd64 pkgconf amd64 1.8.1-1
103.8   Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 Err:60 http://deb.debian.org/debian bookworm/main amd64 pkg-config amd64 1.8.1-1
103.8   Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 Fetched 62.8 MB in 1min 28s (711 kB/s)
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/g/git/git-man_2.39.2-1.1_all.deb  Could not connect to debian.map.fastlydns.net:80 (146.75.2.132), connection timed out Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/g/git/git_2.39.2-1.1_amd64.deb  Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]  
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkgconf/libpkgconf3_1.8.1-1_amd64.deb  Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkgconf/pkgconf-bin_1.8.1-1_amd64.deb  Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkgconf/pkgconf_1.8.1-1_amd64.deb  Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 
80]
103.8 E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkgconf/pkg-config_1.8.1-1_amd64.deb  Unable to connect to deb.debian.org:http: [IP: 146.75.2.132 80]
103.8 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: process "/bin/sh -c apt-get update \t&& apt-get install -y --no-install-recommends \tgit \tpkg-config \tdefault-libmysqlclient-dev \tgcc \t&& rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by poyrazogluyigit** [comment]
I've modified the dockerfile. Could you pull and try again?

**Comment by kristinatrajkovski** [comment]
Just did and it works! Great job!

**Comment by Mutti499** [comment]
I literally deleted my wsl while trying to download docker. I loved the usage logic of Docker, but it drove me crazy in terms of usage and I hated this task. I congratulate @poyrazogluyigit for his patience and effort.

**Comment by poyrazogluyigit** [comment]
Thanks everyone for testing my configuration. A newer and more comprehensive issue has been opened and we should move the discussion there.
