### ISSUE TITLE
[Ceylin, Berkay] Create RAM diagrams

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#147]
Responsibility Assignment Matrix (RAM) is an important diagram to track, review and make an assessment of distribution of responsibilities among team members; this task heavily requires attention and remembering completed tasks. Since it is highly open to overlook some responsibilities at past, feedbacks and thorough reviews are highly appreciated.

Deadline: 27.04.2024
Estimated effort: 1 hour
Reviewer: @halil-karabacak @kristinatrajkovski @Mutti499

**Comment by ceylingebes** [comment]
@berkaykeskino and I have created the responsibility matrix. You can check it from [here](https://github.com/bounswe/bounswe2024group9/wiki/Responsibility-Assignment-Matrix-(RAM)). Since there are exhausting number of tasks and accomplishments (congrats to y'all) it is high chance that we missed or forgot some of them. Please check your personal contributions/roles and inform us if there is some problems. @ErayEroglu @mehmeteminipekdal @Mutti499 @halil-karabacak @kristinatrajkovski @ahmetcicekk006 @baycici @poyrazogluyigit @Taha-Topaloglu

**Comment by Mutti499** [comment]
I can't believe you managed to pull this off. You really examined all of our tasks and made arrangements. We asked everyone to make small updates based on their own information. Thank you. You are amazing!

**Comment by ErayEroglu** [comment]
It looks very good, I don't wanna think about the time you spent on this. My part seems very accurate, elinize saglik

**Comment by ceylingebes** [comment]
Thanks for your feedbacks <3 now I'm closing the issue as closed.

**Comment by halil-karabacak** [comment]
Wow, guys. Just read the whole section and I enjoyed much reading it. Good job!
