### ISSUE TITLE
[Berkay, Emin] Create static route examples

### ISSUE THREAD

**Issue by berkaykeskino** [bounswe/bounswe2024group9#149]
It is decided to put static search result examples under wikidata search result. So we need to implement result components that look like mock ups.

* [x] Create the component
* [x] Add it to the original page.

Deadline: 27.04.2024
Estimated effort: 1 hour
Reviewer: @Mutti499 @kristinatrajkovski

**Comment by Mutti499** [comment]
How is it going guys? Lets keep it quick. The deadline is cominngg!!

**Comment by berkaykeskino** [comment]
It is almost there! It will be done by 20.00 I guess.

**Comment by ceylingebes** [comment]
I am seeing a pull request #154 related to this issue. Since I have reviewed this PR and we merged it with @Mutti499 and @berkaykeskino , I am closing this issue. Thanks for your efforts.
