### ISSUE TITLE
[Kristina, Mutti] Web Authentication

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#150]
Right now even users who are not logged in can access the search and results pages. We should be able to limit that to logged in and therefore registered users. 

Make sure to test the effects thoroughly. No functionalities from before shall be lost, only updated.

Deadline: 28.4.2024.
Estimated effort: 3-4 hours
Reviewer: @ceylingebes

**Comment by kristinatrajkovski** [comment]
Implemented this at [bd10834](https://github.com/bounswe/bounswe2024group9/commit/bd10834555a1f9bfa594eaa831ca4a50c5c43789). It definitely needs some revising and testing.

**Comment by Mutti499** [comment]
We did a really high quality job. A big part of the success belongs to @kristinatrajkovski , but never underestimate my legendary 
 error hiding tactic after the logout. The idea wasn't bad at all!
