### ISSUE TITLE
[Everyone] Test deployed applications and provide helpful feedback.

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#156]
I don't know who is available for this job, but I don't want you to see for the first time what we will show in tomorrow's demo. I want everyone to test the deployed server and have an opinion and give feedback if they think it is important.

**Comment by ahmetcicekk006** [comment]
I don't know if there is a time to make changes but I want to provide some feedback
1)After searching for a place,Nearby Locations button returns a list but it looks ugly
2)Background image of login and signup pages are not the same as that of mock-ups
3)When I search for "ce",the search engine returns all place that contains "ce" as substring,like "Topkapi Palace".
4)Some location names,like "Istanbul Commerce University", are translated to English,which is weird
5)After clicking on go back button on the page for a location,the previous search result is gone.I have to type the same thing again and again
6)Forget password and remember me boxes are not functional
7)Some locations like Rumelifeneri,Ortakoy Jewish Cemetery,Yukari doesn't have image,I have encountered many more but I can't remember their all of their names

**Comment by Mutti499** [comment]
Nice and quick feedback. I am currently developing the web app. You can join me!

**Comment by kristinatrajkovski** [comment]
> I don't know if there is time to make changes but I want to provide some feedback 1)After searching for a place,Nearby Locations button returns a list but it looks ugly 2)Background image of login and signup pages are not the same as that of mock-ups 3)When I search for "ce",the search engine returns all places that contain "ce" as substring,like "Topkapi Palace". 4)After clicking on go back button on the page for a location,the previous search result is gone.I have to type the same thing again and again 5)Forget password and remember me boxes are not functional 6)Some locations like Rumelifeneri,Ortakoy Jewish Cemetery,Yukari,İçmeler/Tuzla Belediyesi don't have image,I have encountered many more but I can't remember all of them 7)The app crushes after searching " ","?","," etc.

@ahmetcicekk006 

1. While I encourage you to create a better *clickable* version please do that after this milestone.
2. If I remember correctly, you were the one who implemented that. Feel free to change with a better option.
3. Works as intended in my opinion. Do you have a better suggestion?
4. Going from a "Search Details" to a "Search Result" page causes that, but even Google's search engine is like that. Besides, going back and forward works as intended between the result details. Again, feel free to suggest a fixing method.
5. Similarly to 2, it was your task to do that, and you can still pitch in even after your teammates had to take over your work.
6. Very normal for Wikidata to not have all of the possible information for all items, same goes for location and inception. Feel free to add a default picture or smth after this milestone.
7. Good catch, maybe you have a suggestion on how to fix it?

While I adress all of your comments, I think we should all have each others backs. It is very easy to make loads of negative comments with little contributions and no suggestions on how to fix the issues. I will be looking into these after the milestone and I kindly invite you to join.

**Comment by ahmetcicekk006** [comment]
I am not critizing anyone and these are not negative comments.This is what giving a feedback is.I thought these may give a negative impression in tomorrow's demonstration session and wanted to share my ideas.I also made comments about my own work.I wasn't the one who implemented backend part and this is why I don't have any suggestion in this short time interval but people who have experience with the backend part may give quick solutions to the problems I mentioned.

**Comment by Mutti499** [comment]
Project submitted! Lets go
