### ISSUE TITLE
[Kristina] Write Unit Tests for API and related Web components

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#160]
You should write unit tests for all the functions you have implemented related to Web and API. Make sure to include the functions where SPARQL queries are integrated, the search and details back end, all about authentication etc. Make sure to have a different test for each function and make it as meaningful and exhausting as possible.

Note: update documentation in these functions if needed.

Deadline: 13.05.2024
Estimated effort: 3 hours
Reviewer: @Mutti499

**Comment by kristinatrajkovski** [comment]
I am trying to update the API documentation with swagger but I am stuck. While I succeeded to create the page and show methods, I am not able to display the descriptions. @Mutti499 can you take a look?

**Comment by Mutti499** [comment]
Of course Kristina! I'm currently investigating the issue

**Comment by Mutti499** [comment]
Hey Kristina I think I made a progress! Look at my basic commit [7044e64](https://github.com/bounswe/bounswe2024group9/commit/7044e644f772df34181751f9ed90f6a2472a1c83). I can proceed with other field if you want?

**Comment by kristinatrajkovski** [comment]
Thank you for the help @Mutti499! Solving that bug was all I needed :) I believe it is done now so please take a look once more.

**Comment by Mutti499** [comment]
I tested your last commit. Great job as always! Lets merge that bad boy  #168

**Comment by Mutti499** [comment]
Oh mamaaa! Saw a liitle problem and fixed it in [8f82bd ](https://github.com/bounswe/bounswe2024group9/commit/8f82bde0feab75fa10768f1d60ef13b633d22dc0). Can you take a loookkk?

**Comment by kristinatrajkovski** [comment]
sorry, I must have missed it with all commits and stashes. Looks good no, thanks for fixing it!

**Comment by Mutti499** [comment]
LGTM
