### ISSUE TITLE
[Kristina] User Test - Mobile Search

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#161]
Write a user test for mobile search. Make sure that:
* all of the testing steps are clearly stated
* the expected result is clearly stated
* the actual result is rated with pass/fail/partial

Include notes, screenshots, videos related to your test. 
Write a bug report (issue) to the responsible developer if any of the steps fail.

Deadline: 12.05.2024 
Estimated effort: 1 hr
Reviewer: @halil-karabacak

**Comment by kristinatrajkovski** [comment]
The testing was completed. The report can be found at the new page I opened [testing](https://github.com/bounswe/bounswe2024group9/wiki/%F0%9F%A7%AA-Testing). Since the test failed I opened the bug #162 . @halil-karabacak do you mind taking a look?

**Comment by halil-karabacak** [comment]
Thanks, it seems we missed a few points. Will be fixing them now and also adding unit tests.

**Comment by Mutti499** [comment]
It is fixed but we forgot to close this. Well done!
