### ISSUE TITLE
Mobile Search Bug

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#162]
This bug report is a result of my user test for mobile's searching. 

* I opened the mobile app from [here](https://github.com/bounswe/bounswe2024group9/blob/main/BuRouteMobile/deploy/app-release.apk) and ran it on my android device
* I logged in with credentials username: "tester" and password: "Tester123"
* I searched for "Hagia sophia"

![WhatsApp Image 2024-05-11 at 21 42 05](https://github.com/bounswe/bounswe2024group9/assets/68972243/a4fa9b9a-3a2f-4494-bb61-cb03b663ed60)

*  I clicked on "Hagia Sophia" result

![WhatsApp Image 2024-05-11 at 21 42 05 (1)](https://github.com/bounswe/bounswe2024group9/assets/68972243/d64d0e78-c961-4dad-922a-782982024a90)

* After seeing the search details, I clicked on "Column of Justinian" from the "Historical Periods" section

![WhatsApp Image 2024-05-11 at 21 42 06](https://github.com/bounswe/bounswe2024group9/assets/68972243/627d7483-5c34-4ebc-8638-d496ce06704a)

* After seeing the search details I clicked on "Haci Besir Aga Fountain" from the "Nearby" section

![WhatsApp Image 2024-05-11 at 21 42 06 (1)](https://github.com/bounswe/bounswe2024group9/assets/68972243/39cffa2b-ee32-4cf4-bcbc-c6f30e18895a)

I was faced with a white screen and the app pretty much crashing. I could not return backwards or do any other actions. An extra note is that this happened with an item which most likely does not contain much information on Wikidata. Please inspect this.

**Comment by halil-karabacak** [comment]
Yeah, it seems this page is missing a Wikipedia page and resulting in crash of the app. Now I added try-catch to all field we are fetching from backend, so I fixed this issue in [commit](https://github.com/bounswe/bounswe2024group9/commit/c6a096b6367ea5c5e0ae0d364a4182d46f3249d7) and tested.

**Comment by halil-karabacak** [comment]
This issue has an PR now #173 .
