### ISSUE TITLE
[Ozgur,Ahmet Burak] User Test- Web Search

### ISSUE THREAD

**Issue by baycici** [bounswe/bounswe2024group9#164]
* State the steps and metrics of the test

* Prepare the report with screen shots and comments

* If encountered with a problem create an issue

Deadline: 16/05/2024
Estimated effort: 2 hours
Reviewer: Yiğit Kaan

**Comment by baycici** [comment]
We have done the user test for Web Search and found no problems or bugs in this part.

**Comment by poyrazogluyigit** [comment]
Can you add the screenshots at the wiki page?

**Comment by baycici** [comment]
Oh my bad thanks for noticing.

**Comment by poyrazogluyigit** [comment]
I haven't seen them yet. Did you add them somewhere else?

**Comment by baycici** [comment]
You should be able to see them now.

**Comment by baycici** [comment]
I believe we have a great testing section [here](https://github.com/bounswe/bounswe2024group9/wiki/User-Test-Visuals-%F0%9F%96%BC%EF%B8%8F) thanks eveybody !!!
