### ISSUE TITLE
[Halil] Write unit-tests for mobile-search

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#167]
* We need units tests for mobile search.

#### Provide a deadline if one is needed
Deadline: 5/13/2024
Estimated effort: 1hr
Reviewer:

**Comment by Mutti499** [comment]
Hey my dearresst friend! Should we consider this solved?

**Comment by halil-karabacak** [comment]
Ay, yeah. This was out of my mind, thanks.
