### ISSUE TITLE
[Ceylin] Write unit tests for mobile login

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#170]
We need units tests for mobile login page.
Deadline: 5/14/2024
Estimated effort: 2 hrs
Reviewer: @berkaykeskino

**Comment by berkaykeskino** [comment]
Hey @ceylingebes ! I see the the amazing work you did in your commit. It looks great, congrats!

**Comment by ceylingebes** [comment]
Thanks, now closing this issue as completed.
