### ISSUE TITLE
[Kristina, Mutti, Ceylin] Route Creation Back End

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#171]
Revise and update the model for route creation. Make sure to include the title, related nodes, photo, descriptions, comments, likes, saves, etc.

Deadline: 11PM 15.05.2024
Estimated effort: 2-3 hours
Reviewer: @poyrazogluyigit

**Comment by Mutti499** [comment]
Seems like a lot more work than 2-3 hours

**Comment by poyrazogluyigit** [comment]
One thing I've noticed is that the system allows empty routes and duplicate routes. Maybe you can implement name checks and/or # of poi checks.

**Comment by ceylingebes** [comment]
We will be dealing this issue ASAP

**Comment by Mutti499** [comment]
I implemented an basic frontend validator for this!

**Comment by Mutti499** [comment]
@poyrazogluyigit can you check one last time?

**Comment by poyrazogluyigit** [comment]
All great! Thanks for your work.
