### ISSUE TITLE
[Halil, Eray] Implement backend functionality for feed

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#172]
#### Feed is an important part of the last milestone, so it is time to do that.

* Posts should be fetched from only the followed users.
* Posts should be shown in the chronological order. More advanced algorithms are not necessary for now.

* [x] Check models to see if database structure is ready for this.
* [x] Implement functions that will be used during feed.
* [x] Test on a mock data.

Deadline: 5/14/2023
Estimated effort: 1hr
Reviewer:

**Comment by halil-karabacak** [comment]
Created the branch [backend/feed](https://github.com/bounswe/bounswe2024group9/tree/backend/feed). Will be doing all the work in there.

**Comment by halil-karabacak** [comment]
Currently backend section should be done. Since I am more familiar with the mobile env. I tested this and got a very basic result which you can see in this ss:
![image](https://github.com/bounswe/bounswe2024group9/assets/73756179/5b810761-9e23-4677-b2ec-d288a7584641)
This may seems nothing but this is actually functional. It gets username from the front-end, then gets the top 10 liked post by the people who the login-ed user follows. So, actually the rest seems the work of frontend rather than backend.

As a final note,
I updated the user model to include:
- following
and route model to include user_id to indicate which user posted which route.

**Comment by ErayEroglu** [comment]
Now i will test it with the web app, if everything is okay i will implement the page

**Comment by halil-karabacak** [comment]
Tested. It is now up to front-end teams.
