### ISSUE TITLE
Revise Front End for Route Creation

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#178]
The route creation's functionalities on the web are mostly implemented. However, 

* the buttons need to look according to our theme
* the search results should be in a much larger container
* remove export since it will not be implemented
* redirect to feed once the route is created

Deadline: 16.05.2024
Estimated effort: 2hrs
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
@berkaykeskino I think there is some work mate! Issue #175

**Comment by berkaykeskino** [comment]
@Mutti499 Yeah I'm working on it, thank you for reminding

**Comment by Mutti499** [comment]
No problem mates. Let me know when it is ready.

**Comment by kristinatrajkovski** [comment]
Changed the front end in the last commit 71823f945f6ee799b23b736ff90a184c27b79aba . Please take a look mates!

**Comment by Mutti499** [comment]
Nice one mate. REALLY GOOD ENDING FOR OUR WEB APP
