### ISSUE TITLE
Database Documentation

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#179]
Please help me out with creating documentation for the database API. I have completed it for wikidata and you can see it on our server at url http://127.0.0.1:8000/wiki_search/swagger/. I believe we need to do the same for all the database endpoints too. 

Deadline: 16.05.2024
Estimated effort: 2hrs
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
It's a pretty big job, let's have a meeting and complete this important task.

**Comment by Mutti499** [comment]
I made a huge commit and it is almost done. This needs to be tested as soon as possible.

#186

**Comment by Mutti499** [comment]
Okey I think people got me wrong when I said almost done I didnt mean finished. However it is enough for this release I guess. The problem at #194  related to here but I solved it. Sooo.. LETS GO!
