### ISSUE TITLE
[Eray] Web Login Needs an Update according to the User Test

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#180]
The results are in! We need to update our siignup page and add kvkk link to that according to [the test results](https://github.com/bounswe/bounswe2024group9/wiki/%F0%9F%A7%AA-Testing#12-web-login-and-signup-authentication-test). Please handle that!

Deadline: 16.05.2024
Estimated effort: 20 minutes
Reviewer: @ceylingebes

**Comment by ErayEroglu** [comment]
I am handling it

**Comment by ErayEroglu** [comment]
can you check if the current version  is okay

**Comment by ceylingebes** [comment]
I am on it, I will update here ASAP

**Comment by ceylingebes** [comment]
Hi there, I just reviewed signup page for web and KVKK link and button are seem to be correctly functioning. Everything seems perfectly done, thank you guys. Closing this issue as completed.
