### ISSUE TITLE
[Mutti, Ceylin, Emin] Add my_routes button in search bar

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2024group9#182]
In our web application there should be my routes page and it should be included in search bar. My routes page shall return the routes which are created by that specific user by fetching data using user ID from the database.

Deadline: 15.05.2024 23.59
Estimated effort: 1 hrs

> Before issue is closed, please don't forget to put a final comment.

**Comment by ceylingebes** [comment]
Pages created and tested collaboratively. Good work everyone!

**Comment by mehmeteminipekdal** [comment]
Page is working correctly. Thanks to everyone!

**Comment by Mutti499** [comment]
LETS GOOO!! WELL DONE
