### ISSUE TITLE
[Ceylin, Emin] Configure the buttons in search bar

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2024group9#183]
* The pages contain different buttons in their search bar.

* There are total of 5 buttons and in every page, other 4 buttons shall be shown.

You may split the issue to tasks if necessary
* [x] Add 4 other pages' buttons on search bar to feed page.
* [x] Add 4 other pages' buttons on search bar to bookmarks page.
* [x] Add 4 other pages' buttons on search bar to route creation page.
* [x] Add 4 other pages' buttons on search bar to my routes page.
* [x] Add 4 other pages' buttons on search bar to discover top routes page.

Deadline: 15/09/2024 23.59
Estimated effort: 1 hour

> Before issue is closed, please don't forget to put a final comment.

**Comment by ceylingebes** [comment]
Buttons are now configured and displaying in all pages now. You can check it our commit [aeccd55](aeccd5523c42e0a56d2422cbacae4e11c357a8e1) for changes. Now closing this issue as closed.
