### ISSUE TITLE
[Mutti, Yigit] Last Deployment

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#187]
Okay, it's time to deploy our application to Digital Ocean for the last time. Let's not waste any time!

Deadline: 16.05.2024
Estimated effort: 2 hours
Reviewer: Everyone

**Comment by halil-karabacak** [comment]
Before deploying please consider 
> path('user_detail/', views.user_detail_from_username, name = 'user_detail_from_username'),
in branch mobile/dev/feed_last_db

**Comment by poyrazogluyigit** [comment]
thank you, but could you please elaborate on what we need to consider?

**Comment by Mutti499** [comment]
Deployed linked and ready to go. What do you say?

**Comment by poyrazogluyigit** [comment]
Yep. We can close this now.
