### ISSUE TITLE
[Ozgur, Emin] prepare a few scenarios that shows the main features of the app

### ISSUE THREAD

**Issue by baycici** [bounswe/bounswe2024group9#188]
* Scenarios should show what is different about the app

* Scenarios should include screan shots from app

You may split the issue to tasks if necessary
* [x] Determine what should the scenarios include
* [x] Take the screan shots from your account
* [x] Write down the scenarios

Deadline: 16.05.2024 11pm
Estimated effort: 2 hours
Reviewer: @Mutti499 

> Before issue is closed, please don't forget to put a final comment.

**Comment by baycici** [comment]
I have written down the first scenario.

**Comment by baycici** [comment]
I have written down the second scenario. You can find them in [here](https://hackmd.io/ZsoTt1jcQ8SGAw0GeFw7Dg?view)

**Comment by mehmeteminipekdal** [comment]
I added the third scenario. And I guess we need one scenario for mobile as well. Please anyone who can contribute, shall add a scenario for mobile application.

**Comment by Mutti499** [comment]
Okey we notified the mobil team about this issue. I am also adding them so that they can see what is happening!

**Comment by Mutti499** [comment]
I don't really remember who was on the mobile team. So I apologize for any mistakes and lef outs.

**Comment by ceylingebes** [comment]
I am unable to do that now due to my doctor’s appointment, not sure how long will it take but I will write here if no one completes this task then.

**Comment by mehmeteminipekdal** [comment]
Scenarios are successfully added to final milestone. Thank you everyone!
