### ISSUE TITLE
[Mutti Kristina Emin] Create mock data

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#192]
For our demo tomorrrow. We need mock data no deadline no reviewer no estimated effort. Just do it !

**Comment by mehmeteminipekdal** [comment]
I added 5 running routes from my account with "naolie" nickname. I think they are cute, and all of them are from my real runs.

**Comment by Mutti499** [comment]
Kristina and I added 20 routes and 4 new users which are not shown in the demo session. Anyways, good job!
