### ISSUE TITLE
[Emin] Create Summary and Status part for final milestone

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2024group9#193]
Update the final milestone, add the summary and status part.

* Write the features that are deployed correctly.

* Write the features that have not finished yet.

You may split the issue to tasks if necessary
* [x] Deployed features are stated.
* [x] Unfinished features are stated.

#### Provide a deadline if one is needed
Deadline: 17.05.2024 19.00
Estimated effort: 2 hours

> Before issue is closed, please don't forget to put a final comment.

**Comment by Mutti499** [comment]
Hey mate can we finish it until tonight?

**Comment by mehmeteminipekdal** [comment]
Successfully done.
