### ISSUE TITLE
[Mutti] Swagger API is not working at remote

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#194]
I dont know why but it is not working when published. I need urgent help

### On remote:
![image](https://github.com/bounswe/bounswe2024group9/assets/75087023/65334231-9014-4159-a254-6b878dc8d20f)

### On local:
![image](https://github.com/bounswe/bounswe2024group9/assets/75087023/13523c25-0a8f-4af0-8d25-73f127460ef8)

**Comment by Mutti499** [comment]
[87c79a](https://github.com/bounswe/bounswe2024group9/commit/87c79a9831b98d74e2d0a4cb51d5a81020e3e98f) woaaa crazy commit for the winn!!! But it needs to be tested for example own routes should be removed. What else!?

**Comment by halil-karabacak** [comment]
I can do nothing but just admire you mutti

**Comment by Mutti499** [comment]
Hey Halil! Bro I am not working at the same time instead of you. I have a lot of free time!

**Comment by Mutti499** [comment]
Okey the problem is solved not it is looking goodd on our remote. Be safe!

https://dolphin-app-zduum.ondigitalocean.app/wiki_search/swagger/

![image](https://github.com/bounswe/bounswe2024group9/assets/75087023/ee387c2a-8146-4c2d-88dc-cb5b4a3a9cda)
