### ISSUE TITLE
Personal Description Pages

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#2]
Create description pages containing information about:
- Short Introduction
- Personal Links
- Interests

- [x] Kristina Trajkovski
- [x] Halil Karabacak
- [x] Mustafa Atak
- [x] Yigit Kagan Poyrazoglu
- [x] Taha Topaloglu
- [x] Muhammed Berkay Keskin
- [x] Eray Eroglu
- [x] Ceylin Gebes
- [x] Mehmet Emin Ipekdal
- [x] Özgür Özerdem
- [x] Ahmet Burak Çiçek

**Comment by Taha-Topaloglu** [comment]
Wrote my personal page and added it to sidebar.

**Comment by baycici** [comment]
Created my personal wiki page
