### ISSUE TITLE
[Kristina] Write Requirements, Mock Ups, and Design Diagrams for Code Execution

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#202]
Write requirements, mock ups, and design diagrams related to the code execution system within the project. Focus on what a user shall be able to see and do within the forum. This task shall be executed together with @damlakayikci and @serhan-cakmak 

To do:
* [x] Clearly communicate tasks with team mates mentioned above
* [x] Write basic requirements for the forum details and code execution
* [x] Create a mobile mockup
* [x] Create a few design diagrams 

Deadline: 05.10.2024.
Estimated effort: 4-5 hours
Reviewers:  @ceylingebes @halil-karabacak

**Comment by kristinatrajkovski** [comment]
Temporary changes and ideas can be seen at https://docs.google.com/document/d/1IuWtdpsW1XWVV5bBSe956glcZfMwgGoCaEH03vkaOaI/edit

**Comment by ceylingebes** [comment]
Looking forward to review your work :)

**Comment by kristinatrajkovski** [comment]
UPDATES:

- Please check the code execution requirements in [this doc](https://docs.google.com/document/d/1IuWtdpsW1XWVV5bBSe956glcZfMwgGoCaEH03vkaOaI/edit). 
- Added a Mockup for mobile code execution at form details at [our project's mockup page](https://github.com/bounswe/bounswe2024group9/wiki/491-%E2%80%90-Mockups)
- Added a code details & execution part in a class diagram, created one of the use case diagrams, and created one of the sequence diagrams. The modifiable temporary version is at [this HackMD page](https://hackmd.io/fzf6bJWFRoq-qmuiNDXoIw) and I have also copied it to [our new design diagrams page](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Design-Diagrams).

@halil-karabacak @ceylingebes  please take a look. While I will be collaborating with Serhan and Damla and supervising their further changes, I believe most of the work on my part is done. I am always happy to hear your ideas and corrections :)

**Comment by damlakayikci** [comment]
I checked them, they look pretty cool. Nice work!

**Comment by serhan-cakmak** [comment]
Nicely done!

**Comment by kristinatrajkovski** [comment]
@ceylingebes @halil-karabacak could you please give this a final review and close the issue if you think it is all complete? thanks

**Comment by ceylingebes** [comment]
I think it looks almost perfect, thank you for your work. Only on the commenting function, we stated “User shall be able to see all the details of a question including the title, a longer description and provided code snippets.” but questions don’t have a title on mobile mockups. Can we fix that? Other than that it looks fine :)

**Comment by kristinatrajkovski** [comment]
Nice catch @ceylingebes , I added the corrected version to the mockups. PTAL

**Comment by halil-karabacak** [comment]
LGTM, nice work. Thanks to all reviewers and Kristina for her hardwork.
