### ISSUE TITLE
[Mutti, Eray] Write Requirements, Mock Ups, and Design Diagrams for Question Search

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#204]
Write requirements, mock ups, and design diagrams related to the question search and browsing system within the project. Focus on how the searching logic should work etc.. 
Complete this tasks with @ErayEroglu  

To do:
* [] Clearly communicate tasks with team mates mentioned above
* [] Write requirements for the forum details and code execution
* [] Create mock ups (for web and/or mobile)
* [] Create a few design diagrams 

Deadline: 05.10.2024.
Estimated effort: 6 hours
Reviewers:  @kristinatrajkovski @serhan-cakmak @damlakayikci

**Comment by Mutti499** [comment]
@ErayEroglu mate I think I nae a great start here https://hackmd.io/@Mutti/Skyd9EYA0. But obviously we need to talk about this and make some decisions about design. Can you take a look?

**Comment by Mutti499** [comment]
I integrated our diagrams with Kristina's work but I am not sure about properties of ProgrammingLanguage. Can you edit that? @ErayEroglu

**Comment by Mutti499** [comment]
According to that properties I will design the filter mockup!

**Comment by ErayEroglu** [comment]
We are working on the mockup design now, we will try to finish and upload them until the end of lab session

**Comment by ErayEroglu** [comment]
I modified the requirements and add some additional ones to the link you provided. Then added them to the wiki page. You may alert me if anything needs a change

**Comment by Mutti499** [comment]
Crazy mockups are ready bro. I am a real artist ofc! Take a looook.
[Notes_241008_163409.pdf](https://github.com/user-attachments/files/17294110/Notes_241008_163409.pdf)

**Comment by ErayEroglu** [comment]
Amazing, uploading them to mockup page

**Comment by ErayEroglu** [comment]
I believe our work is done here, so I am closing the issue. Working with you is a 	privilege @Mutti499
