### ISSUE TITLE
[Kristina, Halil] Create Long-Term Project 

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#205]
In order to get a clear vision of our milestones and assigned issues and groups we should create a visual representation of a long-term project. ProjectLibre is a suggested tool but we may look into something else as well. 

* [x] Brainstorm deadlines/topics/assignments
* [x] Create a clear timeline with highlighted milestones
* [x] Get feedback from the team

Deadline: 08.10.2024.
Estimated effort: 2 hours
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
Good descrpiption mate! Waiting your good work eagerly.

**Comment by kristinatrajkovski** [comment]
Added a draft to the side bar
[451.Group.9.pdf](https://github.com/user-attachments/files/17269127/451.Group.9.pdf)

@halil-karabacak please take a look and let me know what you think we should add/modify

**Comment by halil-karabacak** [comment]
Maybe some dates are a little bit earlier than they may took but looks good, nice work!

**Comment by Mutti499** [comment]
Sorry mate my bad! I checked it and it looks okey I will say LGTM next time
