### ISSUE TITLE
[Emin] Write Requirements, Mock Ups, and Design Diagrams for Login Logout Sign Up and Profile

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2024group9#206]
* Create requirements, mock ups, and design diagrams related to logging in and out, signing up and profiles within the project. 
* Choose a compatible color for all of the pages.
* Complete these tasks with Fatih Akgöz 

To do:
* [x] Communicate with other members about the consistency
* [x] Write requirements for the profile pages and signing in/up
* [x] Create mock ups (for web and/or mobile)
* [x] Create design diagrams 

Deadline: 05.10.2024.
Estimated effort: 6 hours
Reviewers: @Mutti499 @ErayEroglu

**Comment by Mutti499** [comment]
He even wrote his description by himself! Nice job mate. I am waiting your great contribution.

**Comment by Mutti499** [comment]
Ey mate what about here? Are we ready to control!!??

**Comment by mehmeteminipekdal** [comment]
Yeah I just lost a little bit too much time for the scenario, sorry for my bad. They will be available soon!

**Comment by mehmeteminipekdal** [comment]
Class diagram additions, use case diagrams and sequence diagrams for profile and signup/login pages can be found [here](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Design-Diagrams). I added Sign Up & Login and Profile requirements [here](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Requirements), I also added some non-functional requirements for sign-up, sign-in and password.

**Comment by Mutti499** [comment]
Mate that login requirements gona kill me at the backend but okey for noww!!
