### ISSUE TITLE
[Ceylin] Write Requirements, Mock Ups, and Design Diagrams for Forum & Feed & Question Creation

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#207]
Write requirements, mock ups, and design diagrams related to the feed, forum and question creation mechanisms within the project. Focus on what a user shall be able to see and do within the forum, what should the feed contain and features of question creation process. This task shall be executed together with @halil-karabacak 

To do:

* [x] Clearly communicate tasks with team mates mentioned above
* [x] Write requirements for the forum details, feed details, question creation
* [x] Create mock ups (for web and/or mobile)
* [ ] Create a few design diagrams

Deadline: 05.10.2024.
Estimated effort: 6-7 hours
Reviewers: @mehmeteminipekdal , Fatih Akgöz

**Comment by mehmeteminipekdal** [comment]
The issue looks extremely important, I’m sure you’ll complete this as soon as possible!

**Comment by ceylingebes** [comment]
My friend @halil-karabacak and I wrote the related requirements, which can be found [here](https://docs.google.com/document/d/1IuWtdpsW1XWVV5bBSe956glcZfMwgGoCaEH03vkaOaI/edit). It is currently a draft, when the others complete their parts of requirements it will be transferred to wiki.

**Comment by halil-karabacak** [comment]
Yeah nice work. I will create a wiki page for requirements and we can add there.

**Comment by ceylingebes** [comment]
The feed and post creation mockups can be found [here](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Mockups) . @mehmeteminipekdal can you review those and close the issue if everything is fine?

**Comment by ceylingebes** [comment]
Sorry, I was experimenting on the Projects section 🙃 @mehmeteminipekdal can you check this out and close the issue afterwards?

**Comment by mehmeteminipekdal** [comment]
I have checked both requirements and the post creation mock up. Everything looks clear I was just confused about sixth requirement which is about labels, maybe we can add the labels part to the mock up as well. Great work!
