### ISSUE TITLE
[Halil] Write Requirements, Mock Ups, and Design Diagrams for Forum & Feed & Question Creation

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#208]
Write requirements, mock ups, and design diagrams related to the feed, forum and question creation mechanisms within the project. Focus on what a user shall be able to see and do within the forum, what should the feed contain and features of question creation process. This task shall be executed together with @ceylingebes 

To do:

* [x] Clearly communicate tasks with team mates mentioned above
* [x] Write requirements for the forum details, feed details, question creation
* [x] Create mock ups (for web and/or mobile)
* [ ] Create a few design diagrams

Deadline: 05.10.2024.
Estimated effort: 6-7 hours
Reviewers: @mehmeteminipekdal , Fatih Akgöz

**Comment by mehmeteminipekdal** [comment]
I appreciate the detailed description and the tasks divided into steps, I am looking forward to seeing the results!

**Comment by halil-karabacak** [comment]
I created a wiki page added the requirements, yet not complete, https://github.com/bounswe/bounswe2024group9/wiki/Requirements-0.1.

**Comment by halil-karabacak** [comment]
I have just added post creation and feed section mockups for our mobile app.
