### ISSUE TITLE
[Damla] Writing Requirements, Mock Ups, and Design Diagrams for Questions & Comments

### ISSUE THREAD

**Issue by damlakayikci** [bounswe/bounswe2024group9#209]
#### Write requirements, mock-ups, and diagrams related to how questions are asked (posts) and answered (comments) in the project. Focus on how a user should contribute to the forum. This task shall be executed together with @kristinatrajkovski  and @serhan-cakmak 

To-do:

* [x] Organize previously written requirements
* [x] Write requirements for the forum details
* [x] Create a few design diagrams

Deadline: 05.10.2024
Estimated effort: 5 hours
Reviewer: @ceylingebes @halil-karabacak

**Comment by damlakayikci** [comment]
Update:
I also added a few diagrams to our [Design Diagrams Page](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Design-Diagrams). I'd be happy to hear your feedbacks guys!

**Comment by serhan-cakmak** [comment]
In commenting sequence diagram, namely 3.2, you may benefit from Alt structure as stated in [here](https://mermaid.js.org/syntax/sequenceDiagram.html#alt). This structure enable you to show the possible user actions in a more clear way.

**Comment by ceylingebes** [comment]
In post creation use case diagram, which is 2.2, I think we wouldn’t need a comment use case for post creator, so maybe we should remove this one?

**Comment by damlakayikci** [comment]
> In post creation use case diagram, which is 2.2, I think we wouldn’t need a comment use case for post creator, so maybe we should remove this one?

I think it will be useful for 2 cases:

1- For replying to the comments of other users
2- The post creator can post their own solution as a reply if they solve the problem after uploading it

**Comment by serhan-cakmak** [comment]
I think the issue should be closed by one of the reviewers ( @ceylingebes, @halil-karabacak ) so that we can make sure that we are all on the same page.

**Comment by damlakayikci** [comment]
Sorry, rookie mistake

**Comment by serhan-cakmak** [comment]
> In commenting sequence diagram, namely 3.2, you may benefit from Alt structure as stated in [here](https://mermaid.js.org/syntax/sequenceDiagram.html#alt). This structure enables you to show the possible user actions in a more clear way.

I edited the diagram as I stated before.

**Comment by ceylingebes** [comment]
What Damla said earlier on that matter seems logical to me. After all, I am closing this issue as completed. Nice work 👍
