### ISSUE TITLE
Create Wikidata Queries

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#211]
Look into Wikidata queries and how they shall be used within out project. Focus on what the API should return from Wikidata (some suggestions are title, description, wikipedia link, language family, similar languages etc.)

The issue shall be closed once we have a query which could be called from the API and which returns info that we can show during our semantic search. 

Deadline - 15.10.2024.
Estimated effort - 4-5 hours
Reviewer: @Mutti499

**Comment by kristinatrajkovski** [comment]
Just a suggestion - I created [this query](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Flanguage%20%3FlanguageLabel%20%3FwikipediaLink%20%3FinfluencedByLabel%20%0A%20%20%20%20%20%20%20%28COALESCE%28%3FpublicationDate%2C%20%3FinceptionDate%29%20AS%20%3Fdate%29%20%20%3Fwebsite%20WHERE%20%7B%0A%20%20%3Flanguage%20wdt%3AP31%20wd%3AQ9143.%0A%0A%20%20OPTIONAL%20%7B%20%3Flanguage%20wdt%3AP737%20%3FinfluencedBy.%20%7D%0A%0A%20%20%23%20Get%20the%20publication%20date%20and%20inception%20date%0A%20%20OPTIONAL%20%7B%20%3Flanguage%20wdt%3AP577%20%3FpublicationDate.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Flanguage%20wdt%3AP571%20%3FinceptionDate.%20%7D%0A%0A%0A%20%20%23%20Get%20the%20official%20website%0A%20%20OPTIONAL%20%7B%20%3Flanguage%20wdt%3AP856%20%3Fwebsite.%20%7D%0A%0A%20%20%23%20Get%20the%20Wikipedia%20link%20%28English%20Wikipedia%29%0A%20%20OPTIONAL%20%7B%20%3FwikipediaLink%20schema%3Aabout%20%3Flanguage%3B%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E.%20%7D%0A%0A%20%20%23%20Request%20labels%20for%20all%20entities%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%0A%20%20%7D%0A%7D%0ALIMIT%2020%0A) which would return a few good labels and links. I think it is a good start, but what other filters and labels do you think we could use @damlakayikci ?

**Comment by damlakayikci** [comment]
I also added a programming paradigm column, but I couldn't find any other useful info on Wikidata. I think it might be better to maybe import the first few paragraphs from that Wikipedia link, I find the info on Wikipedia more understandable. What do you think? Is it possible we do that way?

**Comment by kristinatrajkovski** [comment]
With a short google-ing session I guess it is possible according to [this stackoverflow Q&A](https://stackoverflow.com/questions/37079989/how-to-get-wikipedia-page-from-wikidata-id). I think it is great, but on the side, maybe we can make use of the "instance of" tag such as [this one for JavaScript](https://query.wikidata.org/#SELECT%20%3FinstanceOf%20%3FinstanceOfLabel%20WHERE%20%7B%0A%20%20wd%3AQ2005%20wdt%3AP31%20%3FinstanceOf.%0A%20%20%0A%20%20%23%20Request%20labels%20for%20the%20instance%20entities%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%0A%20%20%7D%0A%7D%0A). Once we have "clicked" on a programming language, for the purpose of the course, I guess we should make sure to link it to other languages as well.

Would you like to open a branch and a draft PR for this? At least to keep the ideas in code and all at one place. I would be happy to jump in

**Comment by damlakayikci** [comment]
Handy link! I wrote a demo code using the method on the StackOverflow link. It worked pretty well, but I still need your revision. I created a pull request. I would be happy if you could give me some feedback!

**Comment by Mutti499** [comment]
How is our pr going?? Should I make the final controls or whatt!!!
