### ISSUE TITLE
[Ceylin] Create RAM Diagrams

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#215]
Responsibility Assignment Matrix (RAM) is an important diagram to track, review and make an assessment of distribution of responsibilities among team members; this task heavily requires attention and remembering completed tasks. Since it is highly open to overlook some responsibilities at past, feedbacks and thorough reviews are highly appreciated.

Deadline: 13.10.2024
Estimated effort: 1 hour
Reviewer: @kristinatrajkovski

**Comment by ceylingebes** [comment]
I have created and shared our initial responsibility assignment matrix for the project based on the issues on our Github. You can found it [here](https://github.com/bounswe/bounswe2024group9/wiki/Responsibility-Assignment-Matrix). I have added all the issues and tasks that don't have a specific issue as far as I can remember, but there can be mistakes ofc. Can you review this @kristinatrajkovski? thanks <3

**Comment by kristinatrajkovski** [comment]
I think the format looks good, but I think some things are missing. Although they might not have an open issue yet, I think it would be nice to see them as a part of the matrix. Database creation, docker, online deployment are some of them, but let me know if you disagree,

**Comment by ceylingebes** [comment]
you are absolutely right. i have added the ones you mentioned as well :)

**Comment by kristinatrajkovski** [comment]
Great job! Please don't forget to update once we have more issues/tasks. Closing for now.
