### ISSUE TITLE
[Halil] Create mobile login, signup, and post details pages

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#219]
#### This is an important issue for the first milestone. So better get started doing it.

You may split the issue to tasks if necessary
* [x] Login Page
* [x] Signup Page
* [x]  Static feed page to let users to click on question details
* [x] Question Details Page

#### 
Deadline: 10.18.2024
Estimated effort: 6hours
Reviewer: @kristinatrajkovski, @damlakayikci

**Comment by halil-karabacak** [comment]
Login and sign-up pages are done. MR can be reviewed here: https://github.com/bounswe/bounswe2024group9/pull/235

**Comment by halil-karabacak** [comment]
Feed and post details page is also completed. I will add few screenshots so the rest of the group members can see the progress: 
![image](https://github.com/user-attachments/assets/95e175aa-7264-4e86-984d-b04caaa1bad6)
![image](https://github.com/user-attachments/assets/f3f0a598-f080-496c-a8aa-0ee99baa3e3f)
The next thing is completion of search page, a few small visual changes related to the position and shape of the search section which i believe looks shitty rn. After that I will focus on backend connection which has its own issue.

**Comment by halil-karabacak** [comment]
PR of Feed and search detail pages can be seen here: https://github.com/bounswe/bounswe2024group9/pull/239

**Comment by serhan-cakmak** [comment]
hey @halil-karabacak you are an absolute beast, yet please wait for us to check your code so that we can make sure that we are on the same page all right? I will reopen the issue, and @kristinatrajkovski will close the issue after testing the apk you mentioned in the pr.

**Comment by halil-karabacak** [comment]
@serhan-cakmak continue in the PR, and if you see a problem create a new issue and i'll fix it. This is issue is only for development and should not exceed its range.
