### ISSUE TITLE
[Serhan] Create User Authorization system

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#220]
The visitors shouldn't be able to run the codes without logging in first. Instead they need to be redirected to the login page. A simple login.html can be added for demonstrating purposes. 

* [x] Create a simple login page.
* [x] Figure out how to authorize the users. 

Deadline: 20.10.2024
Estimated effort: 3h
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
I became a reviewer for your task.. How gratefull am I

**Comment by Mutti499** [comment]
welcome back mate!

**Comment by ceylingebes** [comment]
Also a quick note: can you check if logout function assigned at /logout endpoint returns the correct response as we discussed earlier @serhan-cakmak ? Its return type is a logout view but a json response could be more convenient imo. If you decide to keep it that way let me know as well.

**Comment by serhan-cakmak** [comment]
This issue is solved in this [pr ](https://github.com/bounswe/bounswe2024group9/pull/254)
