### ISSUE TITLE
[Kristina] Wiki Search/Result API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#222]
We need to be able to search wikidata and see resulting information and links from it. 

Search:
* [x] Take string input from user
* [x] Support multiple word input
* [x] Return at most 5 matches if available
* [x] Return the labels (will be shown to user) and wiki id's (will be used internally for results)

Result:
* [x] Take wiki id as input from internal sources
* [x] Return wiki label, influenced by tag, date of creation, website
* [x] Connect to wikipedia response from #211 

* [x] Write unit tests

Deadline: 18.10.2024
Estimated effort: 4 hrs
Reviewer: @damlakayikci

**Comment by damlakayikci** [comment]
Checked it just now, looks awesome!! Nice work!
