### ISSUE TITLE
[Mutti] fix bugs ont he code and update the design of wiki

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#224]
Okey may seem like a odd issue but I noticed some random unncessary stuff around here: 

- [x] we have a lot of unused branch that left from the cmpe352, 
- [x] I had created an issue type and it became a frustration for us.
I will control them and delete them of course!

Deadline: 20.10.2024
Estimated effort: 15min
Reviewer: @serhan-cakmak

**Comment by Mutti499** [comment]
I deleted a LOT of my old branches! Lets go

**Comment by Mutti499** [comment]
Kristina was right all along.. I didnt used that issue template at all! I deleted that in the [commit](https://github.com/bounswe/bounswe2024group9/commit/080e9f0e874d5e9d1cae77ee9acdb308fb2ff274). @serhan-cakmak check that out!

**Comment by serhan-cakmak** [comment]
I checked out the dates of the remaining branches, they are all new. Good job!
