### ISSUE TITLE
[Mutti, Damla] Create models and endpoints for creating them

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#225]
It is time to pace up!
We need 4 classes for starter:
- user
- langQuestion
- questionComment
-  ~programmingLanguage~
and endpoints for creating and controlling them such as:
- login
- register
- searchLanguage
If anything more we can discuss that later. We need to be fast since @serhan-cakmak is waiting for us in [the issue](https://github.com/bounswe/bounswe2024group9/issues/220) and I dont want to interact with him much..

My english is dead. Lets start

Deadline: 19.10.2024 02:00
Estimated effort:  4 hours
Reviewer: @serhan-cakmak @kristinatrajkovski

**Comment by Mutti499** [comment]
OPkey we had a good start in the models with commits [here](https://github.com/bounswe/bounswe2024group9/commit/a6704461a40399ce1d2dea123831532bb3737a06#diff-06207fb93b42ae111238f2f44005d95eeb343886166b122b19561bda10c8543fL27). But lets continuee!

**Comment by Mutti499** [comment]
Crazy [commit ](https://github.com/bounswe/bounswe2024group9/commit/f06e4181719ffbad93bd13f7970ed48a70219fa2)is ready! I think it will give a lot of functionality to our userr but now the [pr](https://github.com/bounswe/bounswe2024group9/pull/221) must have some adjustments!

**Comment by damlakayikci** [comment]
Oups! Just after I wrote the ProgrammingLanguages class, I saw this message 😅. Never mind, I'll work on the endpoints!

**Comment by Mutti499** [comment]
Nice commit from @damlakayikci for listing questions with a filter! But we need to fix running code endpoint with a little help of @serhan-cakmak . I am opening an issue rn.

**Comment by Mutti499** [comment]
Serhan is a bit of a shy guy, but I can tell he handled the situation very well.
