### ISSUE TITLE
[Eray, Ceylin] Implement the Frontend of Web Application

### ISSUE THREAD

**Issue by ErayEroglu** [bounswe/bounswe2024group9#226]
Login/signup, search and code execution pages must be implemented till the milestone.

* [x] Implementation of the login/signup page
* [ ] Implementation of the search page
* [x] Implementation of the code execution page

Deadline: 21.10.2024
Estimated effort: 6 - 8 hrs
Reviewer: @Mutti499

**Comment by ceylingebes** [comment]
initial version of login, sign up pages are implemented in commit a6681cedc2c81be0ea13113336eb5399226b8d6e. note that its design files (.css) are not finalized, it needs development and its endpoints need to be arranged correctly.

**Comment by ErayEroglu** [comment]
I also created a new branch for myself and merged it with the backend part. Then created an initial design for the [code execution page. You may examine this [commit](https://github.com/bounswe/bounswe2024group9/commit/d984e62109247f974cdcc135c4c10af3e8c47cb9).  Everything is static for now.

**Comment by ErayEroglu** [comment]
Also implemented the syntax highlighting logic, I think we may merge our works into web-frontend @ceylingebes

**Comment by ErayEroglu** [comment]
Design for all pages are done, now we must connect the backend to our application.

**Comment by serhan-cakmak** [comment]
@mehmeteminipekdal please keep us updated.

**Comment by ErayEroglu** [comment]
@serhan-cakmak implemented a dynamic code runner and integrated that to our question details page, thanks for the support

**Comment by ErayEroglu** [comment]
I believe we are done after the [final fix](https://github.com/bounswe/bounswe2024group9/commit/92a191e815d91e73dd3d92a77f0dc6c026f215b5). Web is ready for tag, it was nice to work with you @ceylingebes . Also thanks for the effort @serhan-cakmak , let's keep up the good work.

**Comment by serhan-cakmak** [comment]
No worries! I enjoyed my time while learning about the details of front end side.
