### ISSUE TITLE
[Mutti, Damla] Dockerizing and Deploying Stuff

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#228]
Okey we all hate it works on my  machine situations. So we need to dockerize our platform so that we can be sure that it is portable and easy to run on all machines! Also after doing that for presentation we need to deploy it. I am not sure how to that but I will try my best! Lets go

* [x] Dockerize the project
* [ ] Deploy the project

#### Provide a deadline if one is needed
Deadline:  21/10/2024 02:00
Estimated effort: 5 hours
Reviewer: @kristinatrajkovski @ceylingebes

**Comment by Mutti499** [comment]
To do that we need to complete [mobile front](https://github.com/bounswe/bounswe2024group9/issues/219), [web front ](https://github.com/bounswe/bounswe2024group9/issues/226) and [our api](https://github.com/bounswe/bounswe2024group9/issues/225).  Lets do them first

**Comment by damlakayikci** [comment]
Hey, I recently pushed changes for dockerization under "dockerize" branch. You can find my pull request [here](https://github.com/bounswe/bounswe2024group9/pull/244). I'd like to hear your feedback!

**Comment by damlakayikci** [comment]
I think we are done here. Thanks for your effort. I'm closing this issue!
