### ISSUE TITLE
[Serhan, Mutti] A little bug for language_id

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#229]
Okey we need some help with language_id for the running the codes. When running a code with the function run_code() we need the code and the language id. The code is of course there but the language id? What is that how can I assign that for example C. We need some lookup table like variable. Can you help to us in [our endpoint issue](https://github.com/bounswe/bounswe2024group9/issues/225)?

Deadline: 20/10/2024 02:00
Estimated effort: 30 mins
Reviewer: @damlakayikci

**Comment by serhan-cakmak** [comment]
Hey @Mutti499 , after our discussion on how we should modify the the run_code function in view.py, I decided to write a new function stated here [link](https://github.com/bounswe/bounswe2024group9/blob/main/django_project_491/django_app/Utils/utils.py#L114) returning ID2language_name and language_name2ID dictionaries so that everyone can reach those dictionaries when needed.

**Comment by Mutti499** [comment]
Yep we handled it with [a good commit](https://github.com/bounswe/bounswe2024group9/commit/9c4beaf558852b2b1feea613f4e2468fc0681b37). I changed the function a bit but I guess we can always return back. Lets goo!

**Comment by serhan-cakmak** [comment]
Hej Hej, @Mutti499  I checked out your commit but I don't see why we needed normalize_language_name function at all. It simplifies the name of the language (ie. Python 3.8.20 to Python), yet why do we lose the ability of running different versions of a language. You probably thought it is not user-friendly to choose versions all the time, yet If we give user a dropdown menu for the language selection including the different versions as different entities I think it would address the problem you mentioned and still offer a wide range of language/version palette

**Comment by Mutti499** [comment]
Oh mate. I didnt know that we will us the names as dropdrown menu items! It makes a lot of sense I will update them shortly

**Comment by Mutti499** [comment]
Okey I fixed the problem [in the commit ](https://github.com/bounswe/bounswe2024group9/commit/2734843b4a854a9d6e041253dbcd59b013ad6073), thanks for the heads up!

**Comment by serhan-cakmak** [comment]
Hey @Mutti499 , I completely change the dict function as i stated [here ](https://github.com/bounswe/bounswe2024group9/pull/236)  . Please check the updated version. Thus I think this issue is solved there. Let me know if you need any help
