### ISSUE TITLE
[Mutti] Prepare more end points for future 

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#250]
Okey the milestone was good. However I know that we know more endpoints and it will cause a burden on us. So I will try to create as many endpoint as possible by predicting future. Also I am thinking of some LLM control but it needs to cooperate with frontend. Additionally in the demo day we really scared about API limitations I will improve that logic in order to make it more reliable.
Lets see!!

Deadline: 02/11/2024
Estimated effort: 3h
Reviewer: N/A

**Comment by Mutti499** [comment]
OKey it is now time to continue with the journey with some endpoints. I am implementing them rn

**Comment by halil-karabacak** [comment]
holy moley! can't wait to see results!

**Comment by Mutti499** [comment]
Okey this is A LOT harder than what it looks. Just end my life..

![image](https://github.com/user-attachments/assets/c16301e2-19b5-49bd-ba4e-90a0c848e5dc)

**Comment by Mutti499** [comment]
We are literally on fire! Backend will be merged main today with the review of @ceylingebes. Thank you in advance.
