### ISSUE TITLE
[Halil] Finalize WEB standart research 

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#253]
So, we have 2 main options for our standart and I am assigned to communicate with the stuff to finalize and inform the team with the decision.

#### Provide a deadline if one is needed
Deadline: 11/20/2024
Estimated effort: 3hrs
Reviewer: @serhan-cakmak @ceylingebes

**Comment by halil-karabacak** [comment]
Still no progress.

**Comment by serhan-cakmak** [comment]
![image](https://github.com/user-attachments/assets/e8eaac9d-aea9-4499-8a93-a99cfca74532)

**Comment by ceylingebes** [comment]
I think we need to discuss it altogether in tomorrow's lab f2f. We can proceed this issue after that
