### ISSUE TITLE
[Serhan] Add Sorting According to Preferences to Code Execution

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#261]
According to the descibed issues in [Lab 6 report](https://github.com/bounswe/bounswe2024group9/wiki/Lab-Report-%236) code execution's back end needs to be updated. The preferred languages of the user gotten from the survey given when signing up should be shown on the top.

Deadline: 12.11.2024. 20:00
Estimated effort: 30 mins
Reviewer: @Mutti499

**Comment by serhan-cakmak** [comment]
After discussing with my teammates, I decided to set the language of the question to be set automatically when user wants to comment. The changes made in web/code_execution branch so anyone who wants to try this feature you are welcome to try it in that branch. That branch will be merged after this [issue](https://github.com/bounswe/bounswe2024group9/issues/275) is solved.
![image](https://github.com/user-attachments/assets/19092309-b965-48ee-966d-c52101f05b3a)

**Comment by Mutti499** [comment]
okey this is a good idea and working. I am approving that!
