### ISSUE TITLE
[Mustafa, Fatih] Add Endpoints for a New Survey Model

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#263]
According to the descibed issues in [Lab 6 report](https://github.com/bounswe/bounswe2024group9/wiki/Lab-Report-%236) the back end models need to be updated according to the survey we will offer after signing up. 
 
* [x] Add a new model
* [x] Test with the chosen preferences
* [x] Connect with code execution and home page

Deadline: 12.11.2024. 20:00
Estimated effort: 30 mins
Reviewer: @kristinatrajkovski

**Comment by Mutti499** [comment]
We completed the task with some help from @serhan-cakmak in [Pr](https://github.com/bounswe/bounswe2024group9/pull/265) !
