### ISSUE TITLE
[Ceylin, Eray, Damla] Update front end according to new UX requirements

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#264]
According to the descibed issues in [Lab 6 report](https://github.com/bounswe/bounswe2024group9/wiki/Lab-Report-%236) the front end pages need to be updated. 

* [x] Update the question page (code execution, make it according to mobile)
* [x] Create the page for the survey
* [x] Add "Question of the day" to the home page

Deadline: 12.11.2024. 20:00
Estimated effort: 30 mins
Reviewer: @serhan-cakmak

**Comment by ErayEroglu** [comment]
I updated the code execution page, now we have syntax highlighter and light mode.

**Comment by damlakayikci** [comment]
I created the survey page and pushed it to Lab6-Ux branch. Don't hesitate to share your feedback with me!

**Comment by ceylingebes** [comment]
I updated the feed and make it display the specific question of the day for the user on top of their feed. I pushed it on Lab6-Ux. You can check it on commit [d15fc6a](https://github.com/bounswe/bounswe2024group9/commit/d15fc6a4a1c8c4a9f8ec3cb27cef9ecce86aea5c).

**Comment by ceylingebes** [comment]
Can you review our commits? @serhan-cakmak

**Comment by serhan-cakmak** [comment]
At first I was afraid, I was petrified
Thinking I could live without this issue by my side
And after spending nights
Thinking how this issue did me wrong
I grew strong
And I learned how to get along

**Comment by ceylingebes** [comment]
DFKJGVNDSRÇLFKV.JSDEGJVL
