### ISSUE TITLE
[Mutti] Fix the logic question of the day

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#267]
Our current question of the day is wrong and giving random question every time the feed page is loaded by a user. Question of the day means that everyone should see one random(maybe choosen somehow) question in the current day even if they refresh the feed page. Lets fix that. 
Note that this improvement will be done in backend improvements branch since it is not merged to the main yet.

Deadline: 14.11.2024. 20:00
Estimated effort: 30 mins
Reviewer: @FatihAkgoz

**Comment by FatihAkgoz** [comment]
I have reviewed the changes and tested the endpoint for daily_question. It works as intended.
