### ISSUE TITLE
[Kristina, Mutti] About wikidata results

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#268]
I had a little problem when navigating in the web frontend. On the feed page, I tried to reach the popular tags shown in the image:
![image](https://github.com/user-attachments/assets/4cfe66dc-11ba-4f3a-ba1f-edf4bf0544ee)

When I tried to go JavaScript, there was no problem:
![image](https://github.com/user-attachments/assets/135414c0-cfcd-47fa-935f-3dc6246a1028)

However, when I tried to reach the Python page, I got an undefined error from the frontend. When I investigated that, I noticed the frontend not getting what it was wanted in field 'inception date'. I fixed the crash problem in the front end; however, I think there may be a bigger issue. On a well-known Python page, we only have a little information.

![image](https://github.com/user-attachments/assets/f5dd7d15-23eb-446e-a095-d52554d016cb)

I tried to see what is returning with Postman and saw the following for Javascript and Python:
Javascript:
![image](https://github.com/user-attachments/assets/d3646d78-bf0a-4f20-9517-186402cdcab7)

Python:
![image](https://github.com/user-attachments/assets/3c128c20-780c-444b-a695-c61b47329c75)

There is missing information, and it is causing problems on the frontend. Can I get some information about how we are planning to improve that part, if we have any? If we may find something to do, like setting the fields while returning from the backend in order to prevent crashes like that.

Can we discuss that? I am calling you because you have a lot more knowledge than I do.
@ceylingebes @kristinatrajkovski

**Comment by kristinatrajkovski** [comment]
There will always be results with null values so we need to make sure to handle such cases when connecting to front end, @ceylingebes maybe you can help with that by adding some null checks to our fields before displaying them in the front.

 For python specifically, great catch @Mutti499, I have investigated the issue and added a few more topics to search in in PR #257 . Now we have much more extensive results when searching programming languages and computer science concepts, including Python.

**Comment by Mutti499** [comment]
Nice job on that! I already fixed the frontend crash problem like I mentioned so there wont a problem also. I will review your pr and close that with our issue
