### ISSUE TITLE
[Mutti] Making loading screens more bearable

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#270]
When users are waiting for backend data to load, the static and uneventful loading screen can lead to frustration and disengagement. To combat this boredom and enhance the user experience, we propose adding a feature that displays random, interesting programming-related facts during the loading process. 
Our new approach will keep users engaged by providing them with short, informative, and sometimes humorous content, transforming an otherwise dull wait into a more enjoyable and stimulating experience. This simple yet effective solution aims to make the waiting period feel shorter and improve overall user satisfaction

Deadline: 15/11/2024
Estimated effort: 1h
Reviewer: @damlakayikci

**Comment by Mutti499** [comment]
i think [this commit ](https://github.com/bounswe/bounswe2024group9/commit/3d2b816df446fe3da0fe922bfeb2c2a970eff324) willl be a good solution for our users. @damlakayikci can you take a look?

**Comment by Mutti499** [comment]
So I am closing this issue with approval. Thank yoouuu

**Comment by ceylingebes** [comment]
I checked what you have done and I think our loading pages are perfect, thank you @Mutti499 <3 I've already implemented loading component to every other page we have connected so far.
