### ISSUE TITLE
[Ceylin, Damla] Refinement in UI/UX in web front-end

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#271]
#### We discussed what needs to be changed in both web & mobile front-end and here are some results that is missing on web right now:

* [x] Make labels in the question body shown in feed clickable.
* [ ] We should have upvote/downvote instead of like as currently is.
* [ ] Remove comment button in feed question body.
* [ ] Search section should be improved. When user typed some query on search bar, it is filtering questions on the feed as well. It should be fixed.

Deadline: 11.17.2024
Estimated effort: 6 hrs
Reviewer: @Mutti499

**Comment by damlakayikci** [comment]
Hey dear back-end developers @Mutti499 @serhan-cakmak! I tried adding upvoting/downvoting functionality to questions from the feed page. I had to modify some files in the backend folder too. However, it's not complete. i didn't want to mess up your work. I guess we need to add upvote and downvote fields to Question table in the database and my increment/decrement functions are also not complete. Can you take a look at it?

**Comment by damlakayikci** [comment]
For now, the upvote/downvote numbers don't show the real values but I added a really nice animation to the buttons 😎

**Comment by Mutti499** [comment]
![image](https://github.com/user-attachments/assets/158e74ee-69ad-47d5-a7f8-654dd9110a4c)

is this broken? Actually, I think it can be but let's test that tonight.

**Comment by ceylingebes** [comment]
Nice work guys! Keep improving

**Comment by damlakayikci** [comment]
Sorry, I didn't see this function oups. I'll modify my changes @Mutti499

**Comment by Mutti499** [comment]
No problem mate. What is our situation about tasks?

**Comment by damlakayikci** [comment]
I am doing pretty well. The upvoting part is mostly done, I added username field to question cards, split the tags so that the language tag is now separate and clickable, other tags are also separated and under language tag.

**Comment by damlakayikci** [comment]
I updated the questions tab on the Language page. Now it looks more structured and it is the same design as Feed questions
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/35bf29a3-84fa-44ee-ad12-102d2df88206">
