### ISSUE TITLE
[Halil] Create profıle page and edit top contributors part for mobile

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#274]
#### We discussed what needs to be changed in mobile front-end and here are some results:

* [x] Create profile page
* [x] Add a top contributors section

Deadline: 11.17.2024
Estimated effort: 4 hrs

**Comment by halil-karabacak** [comment]
I have created the user profile page which uses android gesture. By swiping from right to left you get where you can navigate through bookmarks, top contributors, and your profile page. For now this side windows looks like this but it will be improved for sure.
![image](https://github.com/user-attachments/assets/842b1580-0cc2-485f-9012-3e34d47a82ea)
The next things is profile page is ready and connected to our backend. This page also requires a little more work but everything is connected to backend etc, so almost there. Now focusing on implementing bookmars and top contributors page.
![image](https://github.com/user-attachments/assets/c08d7ca4-336e-4f00-9232-7ba96e13c09d)

**Comment by halil-karabacak** [comment]
Top contributors is implemented as well. Here is how it looks like:
![image](https://github.com/user-attachments/assets/31ed44e4-16ef-4ca4-8a5c-82490a10328e)
![image](https://github.com/user-attachments/assets/1db2b030-966b-4490-aa82-7192ea021141)

it seems we have an issue with profile photos, they will be dealt with.

**Comment by halil-karabacak** [comment]
Update the branch with the latest backend:
eaec1d3 - Merge remote-tracking branch 'origin/main' into mobile-refinement-in-ui-of-mobile
