### ISSUE TITLE
[Fatih, Serhan] Question Details Page Improvements

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#275]
- [x] Make the page dynamic based on question
- [x] Add upvote and downvote buttons
- [x] Create Add Update answers
- [x] Add tags
- [ ] Add navigation bar for home, profile, search etc.

Deadline: 19.11.2024
Estimated effort: 20 hrs
Reviewer: @Mutti499

**Comment by Mutti499** [comment]
We also need to be able to mark comment as question's answer if it is the owner of the question and see the comments marked as answer. Please refer to the question_views.py

**Comment by FatihAkgoz** [comment]
Added layout for question and comments
Added buttons regarding upvotes
Added post and comment owners name
Added related tag and language information
