### ISSUE TITLE
[Mutti] Add even more functions for backend

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#278]
Okay last part was good but when we investigated requirements today we noticed that we are really behind the schedule. I still need to write a lot of view functions. So let's start with:

- [x] - Adding name and surname to the user model
- [x] - Adding a profile picture
- [x] - Adding endpoint for bookmarking
- [x] - Finding what to do with reported posts
- [ ] - Finding what to do with super users
- [x] - Implementing super user.
- [x] - Implementing password reset mail and functionality.
This can't be that hard, is it?

Deadline: 20.11.2024
Estimated effort: 10 hrs
Reviewer: @ceylingebes

**Comment by Mutti499** [comment]
Okey first part is completed with [the commit](https://github.com/bounswe/bounswe2024group9/commit/4cb730bb68ff9ffd9cf2961703caabf1334ff788). I don't know what to do with super user and reported users yet...

**Comment by Mutti499** [comment]
For example, in my [latest commit](https://github.com/bounswe/bounswe2024group9/commit/422bda66e523e80212d41833fec7447a1e65931f) I added a URL to randomly select a reported question. We can give superusers the option to review reported questions so they can be deleted.

**Comment by ceylingebes** [comment]
Also about the password reset, I am working on password reset page and I'm about to complete it but I don't know how to connect user-specific links that we send via mail to that page. Can we have a look on it tomorrow?

**Comment by Mutti499** [comment]
Ye I noticed it also now the problem is solved and I implemented resetting on the front end. Enjoy
