### ISSUE TITLE
[Mutti] Keeping track of corrected fav repositories 

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#28]
I am opening this issue to reference from Meeting Notes. It is not a task, 

If you update your fav repo or think that the version you posted is complete, please mark it. So I can keep track of this. 

If you opened an individual issue, please mention it in the comments so they will be gathered and organized here.

- [x] Mehmet Emin İpekdal
- [x] Halil Karabacak
- [x] Mustafa Atak
- [x] Yiğit Poyrazoğlu
- [x] Taha Topaloğlu
- [x] Berkay Keskin
- [x] Eray Eroğlu
- [x] Ceylin Gebeş
- [x] Kristina Trajkovski
- [x] Özgür Özerdem
- [x] Ahmet Burak Çiçek

**Comment by Mutti499** [comment]
Since I am not allowed assign to everyone and I want to inform all of you to do it, here we go:
@ErayEroglu  @ceylingebes @kristinatrajkovski @Taha-Topaloglu @mehmeteminipekdal @halil-karabacak @poyrazogluyigit @berkaykeskino @ahmetcicekk006

**Comment by Mutti499** [comment]
My own task:
[Issue #26 ](https://github.com/bounswe/bounswe2024group9/issues/26)

**Comment by Mutti499** [comment]
Ceylin's Task:
[Issue #21 ](https://github.com/bounswe/bounswe2024group9/issues/21)

**Comment by Mutti499** [comment]
Kristina's Task:
[Issue #14 ](https://github.com/bounswe/bounswe2024group9/issues/14)

**Comment by Mutti499** [comment]
Berkay's Task:
[Issue #25 ](https://github.com/bounswe/bounswe2024group9/issues/25)

**Comment by ErayEroglu** [comment]
Roger that

**Comment by halil-karabacak** [comment]
The repo I shared seems to fit well the critera, no changes needed. #29

**Comment by poyrazogluyigit** [comment]
The repositories in my link are also adequate. ![#35]

**Comment by ceylingebes** [comment]
My repository & explanation of it seems adequate as well. [#21 ](https://github.com/bounswe/bounswe2024group9/issues/21)

**Comment by baycici** [comment]
#34

**Comment by ErayEroglu** [comment]
I corrected my repo, sorry for the delay

**Comment by ceylingebes** [comment]
a mini reminder for @mehmeteminipekdal in case you have updated your fav repo and update this issue 🙃

**Comment by mehmeteminipekdal** [comment]
Successfully done.

**Comment by Mutti499** [comment]
Well done team!
