### ISSUE TITLE
[Mutti] Adding docs to the backend functions with assistant tools

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#282]
Well, even if the functions work fine, we need explanations of what they do so that the other team members can understand the function's purpose. Since I write most of this backend code, I will also write the explanations. Since it takes a relatively large amount of time to do this, I am thinking of getting help from models like the GitHub copilot and editing what they write, but if they do not do a quality job, I will write it myself. Let's say everything is for the better understanding of other friends. 

Deadline: 25.11.2024
Estimated effort: 4hrs
Reviewer: @serhan-cakmak @damlakayikci

**Comment by Mutti499** [comment]
@serhan-cakmak didnt write a comment but it is merged so I am taking it as completed

**Comment by serhan-cakmak** [comment]
As I know, if you connect the issue correctly to the pr, when the pr is merged issue closes automatically. Isn’t it the case?
