### ISSUE TITLE
[Mutti] ADDING AI TO THE APPLICATION

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#283]
My mom told me not to ruin my life by using LLM. My friends told me it was useless and that I shouldn't deal with it no matter what I do. Cmpe 443 teacher Arda put the midterm at the same time as the 2nd milestone just because of this. My company begged me not to steal Claude Haiku's keys from them.

But no. It's time. With AI everywhere in our lives, we need to put ourselves one step ahead of others and use this technology for a better interface in our project. My plan is to use LLM to take random posts created by users (I think the current rate is 10%) and check them. If there is a problem, it will let us know and we will automatically prevent the question from being published.

Is it impossible? I said I will always do my best for my teacher @suzan-uskudarli . I hope I won't die.

Deadline: 27.11.2024
Estimated effort: 5hrs
Reviewer: @serhan-cakmak

**Comment by halil-karabacak** [comment]
kidding? this can't be true!

**Comment by Mutti499** [comment]
I have to..

**Comment by Mutti499** [comment]
@serhan-cakmak didn't write his thoughts from here but there is no problem except the randomness. I hope in the demo it won't cause a problem

**Comment by serhan-cakmak** [comment]
Oh, I was so shocked about how you handled this ai enhancement in this [pr](https://github.com/bounswe/bounswe2024group9/pull/285) I happen to forget about this issue. Great contribution @Mutti499 , I wonder what other cards you have in your hand 🤩
