### ISSUE TITLE
[Mutti] Backend is too slow

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#292]
After some merges, the app started to run incredibly slow. The number of requests made from the front end side is overwhelming the backend. The backend should be able to call other functions internally to deduce the requests. If help is needed, the assignee can reach @serhan-cakmak for additional help.

Deadline:  21.11.2024
Estimated effort: 4h
Reviewer: @kristinatrajkovski

**Comment by damlakayikci** [comment]
yess @Mutti499 Let's do it!!

**Comment by Mutti499** [comment]
I made an improvement at the branch that reduces the time taken. Take a look at the PR and compare the results, please.

**Comment by kristinatrajkovski** [comment]
![image](https://github.com/user-attachments/assets/fd19c808-fcdc-4618-8f7c-4d450f553968)

Hi, I noticed that after we add annotations we will have three separate requests on the search results page. Can we improve that?

**Comment by Mutti499** [comment]
on it mate!

**Comment by Mutti499** [comment]
Sorry this issue needs to be revised also. I didn't completed all the tasks about this issue.

**Comment by Mutti499** [comment]
yep new PR is now open and ready to go
