### ISSUE TITLE
[Mutti] Alert is a bad design choice

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#323]
Seeing the backend results as an alert when there is a problem is controllable from a development perspective, but it causes a really bad experience for the user. I used to impoemente a notification style sweet pop up for this purpose, I should review it and integrate it into our app.

Deadline: 08.12.2024
Estimated effort: 2 hrs
Reviewer: @damlakayikci

**Comment by Mutti499** [comment]
This [PR](https://github.com/bounswe/bounswe2024group9/pull/324) should make the difference.

**Comment by damlakayikci** [comment]
Wow, I tried it just now, it looks really nice and user-friendly!

**Comment by Mutti499** [comment]
Nıce I am closıng the pr after the comment of Kristina!
