### ISSUE TITLE
[Fatih, Emin] Domain-specific Features

### ISSUE THREAD

**Issue by FatihAkgoz** [bounswe/bounswe2024group9#328]
Domain-specific features (e.g. why they're specific, how they're implemented):
- [x] **Improvements on syntax highlighting in code execution blocks:** In the code execution blocks that users can add in their questions, syntax highlighting is implemented in order to improve readability of the code. It also improves user experience since it provides a familiar environment that programmers usually make developments. The implementation of syntax highlighting was initialized, not finalized, but it should be improved based on the feedback we got from customer. There is syntax highlighting as it is on milestone 2, but not all the keywords or conventionally highlighted elements are highlighted. Also it should be more engaging visually in terms of colors etc. Also if it's possible -it's in the scope of the syntax highlighter API we use- language-specific highlighting should be implemented. If the API we were using to implement syntax highlighting permits to make those changes, these should be implemented as well.
- **Acceptance Criteria:** _There should be language-specific syntax highlighting with more engaging color palette._
- **Example Usage:**
![syntax-highlighting](https://github.com/user-attachments/assets/79c50ea5-6119-4f53-978f-678f166ee168)

- [x] **Improvements on code execution output display:** The output of the code snippet that has run by user should be visible right below the aforementioned snippet. Since we are working on a programming language forum, the conventional code running mechanisms and designs should be implemented to gain acceptance by the community. This would improve user experience significantly and needed to be improved based on the feedback we got from customers. In milestone 2, there were bugs that causes to outputs to displayed at the end of the question details page. It should be displayed in a more visually logical place.
- **Acceptance Criteria:** _The output of the code snippet should be displayed at the right under the related code snippet, under the "Run Code" button._
- **Example Usage:** [Code Execution Web Mockup](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Mockups#web)

_Originally posted by @ceylingebes in https://github.com/bounswe/bounswe2024group9/issues/326#issuecomment-2514549397_

**Comment by FatihAkgoz** [comment]
Code execution outputs were seperated for questions, comments and try your own code sections.

**Comment by FatihAkgoz** [comment]
Since syntax highlighing caused issues integrating annotations we have decided to prefer annotation for code blocks.

**Comment by mehmeteminipekdal** [comment]
Syntax highlighting issues are resolved and highlighting is added to frontend.
