### ISSUE TITLE
[Ceylin] Add Discussion Posting into Web

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#337]
As we have decided in Lab 8 and also according to the feedback we got from customers, mentioned in [PR #326](https://github.com/bounswe/bounswe2024group9/pull/326), we need to create a new post type named as discussions for our web application. The related acceptance criteria and example usages are stated below:

"Users shall be able to just discuss on the forum without posting a question.

Acceptance Criteria:
A discussion section will be introduced where users can post open-ended topics without marking them as questions.
Example Usage:
User creates a new discussion thread about "The future of AI in education" and receives comments from other users."

You may split the issue to tasks if necessary
* [x] Differentiate post types for discussions or questions in feed
* [ ] Differentiate post types for discussions or questions in question details page
* [x] Add discussion and question tabs for post creation page

Deadline: 13.12.2024
Estimated effort: 2 hrs
Reviewer: @kristinatrajkovski , @halil-karabacak

**Comment by Mutti499** [comment]
I came here to help my friend Ceylin about backend. [In my last commit](https://github.com/bounswe/bounswe2024group9/commit/79d6cc0cdc0377a2ededd6848ce3b7e1d7261439) added:
- Adding question type. Changing adding and editing functions according to that. Improving backend
- Change bookmark logic.
- Fixing feed post frontend a big time.
- Removing horrible check_bookmark function.

**Comment by ceylingebes** [comment]
Just for the update: I have completed the changes in the feed and post creation pages. I am waiting for question details page since our friend Damla is making huge changes there.
