### ISSUE TITLE
[Damla, Fatih] Modify Question Details Page

### ISSUE THREAD

**Issue by damlakayikci** [bounswe/bounswe2024group9#340]
#### The question details page looks awful. My job is to make it more functional and make it look more pleasing
![WhatsApp Image 2024-12-10 at 16 02 24](https://github.com/user-attachments/assets/daa9ccaf-aa95-437e-97dc-7d765aefe884)

The main tasks:
* [x] Add line numbers to the code snippet field
* [x] Change the overall design (to make it visually more pleasant)
* [x] Move the result of code execution right under code snippet block
* [x] Move comment button under the question
* [x] Make it possible to make comments without adding code snippet and language
* [x] Create a separate output box for 'Try Your Own Code' field

Deadline: 17.12.2024
Estimated effort: 10 hrs
Reviewer:

**Comment by FatihAkgoz** [comment]
Currently if the code snippet and language are left empty comments are created without code snippet.
