### ISSUE TITLE
[Eray, Ceylin, Damla, Fatih] Navigation from Profile Page to Feed

### ISSUE THREAD

**Issue by ErayEroglu** [bounswe/bounswe2024group9#342]
* Users should be able to navigate from their profile page comments section to the question they commented. As far as I know nobody works on this page, so it would be great if one of us can work on this.  When someone have time to work on this, please let the rest of us know that you are starting to work on it and the others can deal with the remaining tasks

* [x] Navigate from profile to feed page

Deadline: 15.12.2024
Estimated effort: 1 hour 
Reviewer: @kristinatrajkovski @serhan-cakmak

**Comment by damlakayikci** [comment]
I did it. It's on my branch 'question_details'
