### ISSUE TITLE
[Mutti] Keeping track of searched topics

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#41]
#### This is a tracker issue used to collect study materials on topics shared by the teacher.

* Please mark it when you complete studying or feeling ready for the next weeks questions about "**_WHAT_**"

* Please share your resources on the topics in the comments section to help others.

- [ ] Mehmet Emin İpekdal
- [x] Halil Karabacak
- [x] Mustafa Atak
- [x] Yiğit Poyrazoğlu
- [ ] Taha Topaloğlu
- [x] Berkay Keskin
- [x] Eray Eroğlu
- [x] Ceylin Gebeş
- [x] Kristina Trajkovski
- [x] Özgür Özerdem
- [x] Ahmet Burak Çiçek

* Deadline: 05/03/2024

**Comment by Mutti499** [comment]
@ErayEroglu @ceylingebes @kristinatrajkovski @Taha-Topaloglu @mehmeteminipekdal @halil-karabacak @poyrazogluyigit @berkaykeskino @ahmetcicekk006 @baycici

**Comment by Mutti499** [comment]
Obvious Research headlines:

- Responsibility Assignment Matrix
- Domain Analysis
- Wikidata, Linked Data, SPARQL semantic queries, Wikidata API
- Keywords requirements and elicitation. (from slides maybe?) 

feel free to correct

**Comment by Mutti499** [comment]
Responsibility Assignment Matrix is an extremely simple matrix chart used to keep track of the people responsible for a task.
Link for the shortest information [here](https://www.wrike.com/project-management-guide/faq/what-is-responsibility-assignment-matrix/)

Wikidata, on the other hand, is like a small door opening into a huge room and needs more studying. However I don't think it's necessary to tinker too much before moving forward. So I am putting [here ](https://www.youtube.com/watch?v=m_9_23jXPoE) a simple short video to check.

Finally, I think we use SPARQL to get data from wikidata with the wikidata api. It reminds me of CMPE 321.. If you want to check it out [here](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial) is the link to the official tutorial on wikidata.

Because my attention span is so short, I'm not sure if the information I collect or share is actually true or a liitle bit false. You can research and give me better information.

**Comment by ErayEroglu** [comment]
I think you tracked enough @Mutti499, you reminders were important since we made our implementation based on these research. At least most of us benefited from the research. After this point, I think we can consider everyone has learnt what they should've. Again, thanks for your effort.

**Comment by Mutti499** [comment]
I totally regret creating the tracker issue. I'm closing this thread by thanking everyone who did their job.

Not you by the way #49 #52
