### ISSUE TITLE
Search and implementation of the Projects section

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#42]
We're testing how Projects Section can be utilized for managing tracker issues, aiming to streamline our process. 

* Deadline: 08/03/2024

* Estimated time:  2-3 hours

> We can get help if anyone has information on this issue.

**Comment by Mutti499** [comment]
It looks like it has more potential than I thought. I need help to design or take actions.

**Comment by kristinatrajkovski** [comment]
Created a new project, explored different opportunities it opens, assigned teammates to new issues, explored issue related labels we can assign (difficulty, priority, deadline, status, etc.)

https://github.com/orgs/bounswe/projects/46

**Comment by Mutti499** [comment]
Good job Kristina!

**Comment by kristinatrajkovski** [comment]
https://github.com/orgs/bounswe/projects/46

Done for now, will be updated as the project goes on.
