### ISSUE TITLE
Specified issue templates will be designed

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#43]
#### We need new issue templates for certain types of issues, such as bug issues or design issues. I randomly assign two people to this task. It can be changed later.

* Deadline: 30/03/2024

* Estimated time: 1 hour

**Comment by Mutti499** [comment]
Hey team, I need your help with a new issue template! I need to create a template for Tracker Issues. 
Deatils can be found at #105. 
Can you design and show it to me for review? @ErayEroglu @ceylingebes

**Comment by halil-karabacak** [comment]
Hi mutti great work! It seems you completed the task but this issue still hanging around, maybe we can close?

**Comment by Mutti499** [comment]
Hey man! I'm still waiting for a bug issue here, but that's because everyone is busy with their work. It is in waiting state I can say

**Comment by Mutti499** [comment]
OKEY.I give up! @kristinatrajkovski , can you modify our classic issue template for the reviewer feature?

**Comment by kristinatrajkovski** [comment]
Our mostly used issue template has been update. As it was reviewed by @Mutti499 as well, I am finally closing this issue.
