### ISSUE TITLE
[Ceylin] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#44]
#### Week 3 research assignment

- [x] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [x] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.08.2024
Estimated effort: 2-3 hours

**Comment by ceylingebes** [comment]
Sorry for the late update 🙏🏻 I did some research on specifically Wikidata and Linked Data in week 3, and focused on SparQL and semantic queries on week 4. I will add my resources on Research page in wiki as soon as possible.

**Comment by ceylingebes** [comment]
I have added my resources after a thorough research under our related esearch page. I beileve they are extremely informative and will be really helpful to gain deep insight and understanding abou the topic. You can find my resources [here](https://github.com/bounswe/bounswe2024group9/wiki/Wikidata,-Linked-Data,-SPARQL-semantic-queries,-and-Wikidata-API-Research#ceylin-gebeş).
