### ISSUE TITLE
[Halil] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#47]
#### Week 3 research assignment

- [x] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [x] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.03.2024
Estimated effort: 2-3 hours

**Comment by halil-karabacak** [comment]
I have completed this task with following a lot of websites some of which I shared under our [research](https://github.com/bounswe/bounswe2024group9/wiki/Wikidata,-Linked-Data,-SPARQL-semantic-queries,-and-Wikidata-API-Research) page.
