### ISSUE TITLE
[Yigit Kagan] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#48]
#### Week 3 research assignment

- [x] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [x] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.08.2024
Estimated effort: 2-3 hours

**Comment by poyrazogluyigit** [comment]
Done (finally)
