### ISSUE TITLE
[Emin] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#49]
#### Week 3 research assignment

- [ ] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [ ] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.08.2024
Estimated effort: 2-3 hours

**Comment by Mutti499** [comment]
Even though I did not talk about the 1st milestone, it is still not nice to see this issue in the 2nd milestone. I'm closing it as incomplete.

No sorry
