### ISSUE TITLE
[Berkay] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#51]
#### Week 3 research assignment

- [ ] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [ ] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.08.2024
Estimated effort: 2-3 hours

**Comment by berkaykeskino** [comment]
Learned a lot!
