### ISSUE TITLE
[Taha] Reasearch Wikidata, Linked Data, SPARQL semantic queries, Wikidata API #44

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#52]
#### Week 3 research assignment

- [ ] Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. 
- [ ] Put specific queries and responses in your Wiki under "research"

#### Topics to research: 
Mobile application development
Web application development
Application Programming Interface (API) use and development

Deadline: 11.08.2024
Estimated effort: 2-3 hours

**Comment by Mutti499** [comment]
I am closing this issue because an extremelly long time has passed. I know we gave the deadline as 11.08.2024 but what is happening here is simply the misuse of good intentions.

I am sorry..
