### ISSUE TITLE
[Mutti] Complete the Elicitation Questions and put them into wiki

### ISSUE THREAD

**Issue by Mutti499** [bounswe/bounswe2024group9#61]
#### Write the Elicitation questions, organize them and put them under wiki

* [ ] Deadline: 17/03/2024

Estimated Time: 2 hours

**Comment by Mutti499** [comment]
For now we have: [Doc Link](https://docs.google.com/document/d/18GKQQi054klGar-2qSFD-BgRuyZmgTekRnNoTwrlrs8/edit)

**Comment by ErayEroglu** [comment]
I added the questions about login /sig in and feed/search bar, also I edit the subtitles.

**Comment by ceylingebes** [comment]
I added the elicitation questions regarding route creation and displaying route details processes and contributed to my teammates' questions in terms of clarification.

I see everyone in our group has completed their parts, so I am closing this issue.
