### ISSUE TITLE
Design Logo for BuRota

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#67]
Design a simple, elegant and topic-related logo for BuRota. This logo will be used in sign up and login pages as well, so it should be a minimalistic one to fit in as well.

* [x] Deadline: 17.03.2024

**Comment by ceylingebes** [comment]
I designed a simple logo using our university's special color palette specifically -since we are BuRota-. It can be found in our Readme [here](https://github.com/bounswe/bounswe2024group9).

 Please give me any feedback you have so I can provide a better, prettier, improved version of it. It is my first time designing an icon, so don't be harsh :D

**Comment by Mutti499** [comment]
Good design Ceylin ! I love it

**Comment by ceylingebes** [comment]
In our weekly meeting, we have discussed the logo and we decided it is satisfactory for a prototype. This issue is now closed.
