### ISSUE TITLE
Create Gannt Chart in Project Libre

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#69]
Gather all of the plans discussed in meetings and present them in a Gannt chart, preferably by using Project Libre as mentioned in class and PS. Include all of the detailed assigned issues from before. About long term plans - make a general plan which will be updated according to the class and project requirements. 

Make sure to include dependencies, participants, important milestones, etc.

Deadline: 17.03.2024.
Estimated effort: 2hrs

**Comment by kristinatrajkovski** [comment]
Created a general Gunnt Chart in Project Libre. The plans must be updated periodically due to new information incoming at all times and huge generalization for the future tasks. 

The results can be seen at the [Long-term planning](https://github.com/bounswe/bounswe2024group9/wiki/Long%E2%80%90term-planning-%F0%9F%93%85) page.

**Comment by halil-karabacak** [comment]
Well done!
