### ISSUE TITLE
Feed: Create Mockups 

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#71]
Create static pages depicting the feed page. Make sure to include both mobile and web examples. Preferably use Figma as agreed with the rest of the team for easier syncing and collaboration.

* [x] Discuss necessary fields, buttons, functions, links on the feed
* [x] Discuss different arrangements of the elements
* [x] Create a web mockup
* [x] Create a mobile mockup
* [x] Update the Mockup Wiki page

Deadline: 16.03.2024.
Estimated effort: 1 hour

**Comment by halil-karabacak** [comment]
I have completed the mock-up page for mobile using Figma in 1 hour.

**Comment by halil-karabacak** [comment]
We discussed briefly over how mobile & web pages should look similar, synced on design choices, and completed the task.

**Comment by kristinatrajkovski** [comment]
The links to our mockups:

[Web Feed Design](https://github.com/bounswe/bounswe2024group9/wiki/Mockups#web-feed-design) (by Kristina)
[Mobile Feed Design](https://github.com/bounswe/bounswe2024group9/wiki/Mockups#mobile-feed-design) (by Halil)
