### ISSUE TITLE
Feed: Add Elicitation Questions

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#72]
Go over the elicitation questions about the feed. Make sure they are exhaustive and detailed. Their answers should clearly depict the expected results. Go over the answers given by the professor and include them in the report.

* [x] Go over the feed related elicitation questions discussed with the team
* [x] Think of other questions
* [x] Add phrases to glossary if you believe a user would not understand a question
* [x] Go over the answers given by the professor

Deadline: 16.03.2024.
Estimated effort: 1 hour

**Comment by halil-karabacak** [comment]
We have added feed design in elicitation questions which you can find in the wiki [page](https://github.com/bounswe/bounswe2024group9/wiki/Elicitation-Questions)
