### ISSUE TITLE
Route: Specify Requirements

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#76]
Provide detailed requirements analysis for route creation and modification. 

* [ ] Deadline: 16 March 2024 19.59

**Comment by poyrazogluyigit** [comment]
We have added the requirements for route creation and configuration to the wiki page. Will be done after migrating a couple requirements.

**Comment by Mutti499** [comment]
Were you able to complete the migration? Do you need help?

**Comment by poyrazogluyigit** [comment]
Waiting on #90

**Comment by poyrazogluyigit** [comment]
#90 is closed, this issue is also done.
