### ISSUE TITLE
Route: Create Elicitation Questions

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#78]
Turn questions that arise during requirement analysis and mockup creation into elicitation question, also come up with new and unique ones.

* [ ] Deadline: 16 March 2024 19.59

**Comment by baycici** [comment]
We went over the requirements, discussed it and decided on the elicitation questions. 
You can find the elicitation questions [here](https://github.com/bounswe/bounswe2024group9/wiki/Route-Creation).

**Comment by poyrazogluyigit** [comment]
[updated:](https://github.com/bounswe/bounswe2024group9/wiki/Elicitation-Q&A)

**Comment by poyrazogluyigit** [comment]
Relevant ones are also migrated. This issue can be closed now.
