### ISSUE TITLE
Route: Create Mock-up Pages

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#79]
Create mock-up pages for:

* Route creation
* Route modification 

for Web & Mobile. Also come up with mock-up scenarios for these pages.

* [ ] Deadline: 16 March 2024 19.59

**Comment by poyrazogluyigit** [comment]
Mock-up pages are created and available on team's figma page. Will be uploaded here once the design is finalized.

**Comment by poyrazogluyigit** [comment]
Mock-up pages are added to the wiki page.

**Comment by Mutti499** [comment]
Great mockups mate! I love the mobile part

**Comment by poyrazogluyigit** [comment]
thanks. waiting on #89, will close one it is done.

**Comment by poyrazogluyigit** [comment]
Done, closing now.
