### ISSUE TITLE
Write User Scenario including feed features and displaying route details

### ISSUE THREAD

**Issue by ceylingebes** [bounswe/bounswe2024group9#84]
The task is to write a user scenario including some basic feed features and displaying route details. Include any mockups that has not been covered by any scenarios as well. Make a background story and include information about the user.

* Deadline: 18.03.2024

**Comment by ceylingebes** [comment]
I have written a user scenario -I believe- meeting these criteria. You can find it [here](https://github.com/bounswe/bounswe2024group9/wiki/Scenarios) titled as **Scenario #2** 

Can you review it and do the final checks about it @Mutti499 before closing this issue as completed? Thanks :)

**Comment by Mutti499** [comment]
I would like to point out here that he did a much more creative job on his own than I did with Eray.  I would like to congratulate him from here too.  well done!

**Comment by Mutti499** [comment]
Omagad I misgendered my friend! There are of course other genders than 2 so i will call Ceylin with THEM pronoun. So sorry about that!

I Would like to congratulate THEM from here too**
