### ISSUE TITLE
[Yigit Kagan] Write Section of Milestone Report

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#88]
Write 'decisions and choices regarding deliverables' section of the milestone report.
* [ ] Deadline: ASAP

**Comment by kristinatrajkovski** [comment]
Good job! I have fixed some minor typos and I suggest adding a section for our Meeting Notes (the takers, the template etc.) and the Weekly Effort section of our Wiki Pages.

**Comment by poyrazogluyigit** [comment]
Thanks!
