### ISSUE TITLE
[Yigit Kagan] Add Work to Report

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#94]
Write all work done so far in a table and add it to the corresponding part of the report. 

* [ ] Deadline: ASAP

**Comment by ceylingebes** [comment]
I believe you have forgotten to assign this to yourself, I assigned it now but please correct if I misunderstood

**Comment by poyrazogluyigit** [comment]
Thanks! I forgot it since I was in a rush. Done now, will reopen if something needs to be added.
