### ISSUE TITLE
[Halil] Complete the Part 4 of Milestone-1 Deliverable 

### ISSUE THREAD

**Issue by halil-karabacak** [bounswe/bounswe2024group9#99]
#### Evaluation of tools and processes you have used to manage the team project. 

* Add this section to the deliverable
* [3/19/2024] Deadline:

**Comment by halil-karabacak** [comment]
Starting to write.

**Comment by Mutti499** [comment]
What is the status of part 4 mate? I believe you did an amazing job

**Comment by halil-karabacak** [comment]
still working on it, only a few sections remaining.

**Comment by halil-karabacak** [comment]
Added git, github, and ProjectLibre to the tools we used and gave a brief explanation of how we think about them.
